### ISSUE TITLE
Branch cleanup

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#101]
I've removed inactive branches and replaced them with tags. But there are some we may not need:

@tcmg https://github.com/GoogleChrome/devsummit/tree/amp-work-2 is yours. Do we still need it?

~~@paullewis https://github.com/GoogleChrome/devsummit/tree/2016-notifications is yours. Do we still need it?~~ It's gone!

~~@surma https://github.com/GoogleChrome/devsummit/tree/2016-webvr is yours. Do we still need it?~~

**Comment by paullewis** [comment]
Get rid from my pov.

**Comment by surma** [comment]
Nah, cull mine.

**Comment by jakearchibald** [comment]
@tcmg *nudge*

**Comment by jakearchibald** [comment]
Removing amp tag. It was a21617000786e77cc05438fa49b7db5fd6a37ce0. @tcmg, let me know if you needed it before it GCs.
