### ISSUE TITLE
Investigate defjam

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#102]
Let's find out how much of this we can customise, and how much we can integrate with it.

* Can we style it?
* Can we query it (eg, can we find out if a user is registered)?
* Can we tell it who the user is? (as in, if they're logged into our site, will they also need to log into defjam?)
* How do they pass completion status back to us?

And anything else interesting you can find.

**Comment by jakearchibald** [comment]
@kosamari can you also find out if we're supposed to set it all up, or if we're going to be given a link? I guess Carol will know.

**Comment by surma** [comment]
I created a test-event to play around with registration. Registration form link: https://events.withgoogle.com/test-chrome-dev-summit-2019/registrations/new/

**Comment by surma** [comment]
As discussed in the meeting, an actual integration withe DefJam API seems unfeasible.

Instead we’ll probably opt to just ask the user if they got a ticket or not.

I’ll consider this ticket blocked for now.

**Comment by jakearchibald** [comment]
We get a link, and that's it. Pfft.
