### ISSUE TITLE
Initial registration design

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#103]
The planning doc contains the elements required. Note that it doesn't include a schedule, but should include info about previous events.

Is 12th July a reasonable deadline for this? There can still be minor tweaks after that, but we should be able to implement from it without big changes. Iterations appearing earlier than that would be useful too!

**Comment by argyleink** [comment]
July 12th 👍

**Comment by argyleink** [comment]
is this complete per the request, or should we update the ticket to include new learned requirements?

**Comment by surma** [comment]
I think this ticket gets closed when we ship to live :)

**Comment by argyleink** [comment]
seems like there isnt much to design here as defjam holds all the functionality and state. i did notice things like emails which could be branded with items from the website, but i dont feel like that's what this ticket was intending to inspire. can y'all help me understand the expectations for this issue? i've just reviewed the planning doc again and wasnt able to find clear answers. thanks!

**Comment by argyleink** [comment]
i'm still unsure of what i'm exactly on the hook for with this ticket.. can someone make it preschool level clear for me?

**Comment by carolrivero** [comment]
Once the email designs are provide for review, then we can create a ticket for you to review but until then, this request is on hold?

**Comment by surma** [comment]
Considering we got everything in place now, I think we can close this.
