### ISSUE TITLE
Implement build system

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#104]
Here are the things I'm trying to achieve:

* [ ] CSS/JS should be associated with an include/layout.
* [ ] Pages only include CSS/JS they need.
* [ ] Ideally, CSS modules.
* [ ] The JS uses code-splitting and bundling.
* [ ] Assets are hashed, including images referenced from the CSS.
* [ ] CSS/JS includes are deduped.
* [ ] As little magic as possible.
* [ ] Watch mode.

**Comment by surma** [comment]
This landed via #105
