### ISSUE TITLE
Semantic HTML

### ISSUE THREAD

**Issue by simevidas** [GoogleChrome/devsummit#11]
Consider using `<header>`, `<nav>`, etc. in the partials; they provide [landmarks for AT](http://mcdlr.com/wai-aria-cheatsheet/) 😋.

**Comment by paullewis** [comment]
Yep, absolutely. I went through the whole site this morning with VoiceOver enabled and I've made a [bunch of changes](https://github.com/GoogleChrome/devsummit/commit/cf1922a3a9a5801d2cc070f1317531a51c4c4074).
