### ISSUE TITLE
Transitions from page to page doesn't seem to load correctly

### ISSUE THREAD

**Issue by didymu5** [GoogleChrome/devsummit#13]
![screen shot 2016-10-10 at 2 50 56 pm](https://cloud.githubusercontent.com/assets/3358652/19252298/085ded1e-8ef9-11e6-99b1-b3e6d1281ef8.png)
Hi Paul find the attached screenshot. I was browsing from page to page and kept getting this miniature version of the page load.  And in some cases the page doesn't load. When I refresh the page loads fine. Chrome Version 53.0.2785.143 
Anyhow, I thought I'd let you know. Thanks for doing the videos!

Tommy

**Comment by paullewis** [comment]
Hey Tommy, thanks for letting me know. It's kinda weird. Does this still happen for you? I've not seen it happen at all for me :-/

**Comment by paullewis** [comment]
Closing as I can't repro, and there doesn't seem to be any other reports of this in the wild.

**Comment by didymu5** [comment]
Ya sorry I didn't get to reply. Ya i stopped seeing the issue as well.
