### ISSUE TITLE
How should we handle super-wide screens?

### ISSUE THREAD

**Issue by surma** [GoogleChrome/devsummit#130]
Current designs go up to 1920px. How should we handle wider screens?

**Comment by argyleink** [comment]
my initial reaction is to cap the width and let any extra space become margin on left/right. good call though! lemme comp it, we can talk about it then.

**Comment by jakearchibald** [comment]
If we cap the width, I imagine that'd be for content inside the modules, so the background colour would still extend full-width.

**Comment by argyleink** [comment]
![supa-wide](https://user-images.githubusercontent.com/1134620/61896152-30afd500-aec9-11e9-8453-3639263cd7f0.png)

lemme know if anything stinks or wasnt thought through enough. but whatchy'all think-o-this?

**Comment by jakearchibald** [comment]
Fixed in https://github.com/GoogleChrome/devsummit/pull/173
