### ISSUE TITLE
“Attend in person” instead of "Register"?

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#131]
Does this fully convey the intent? Will the user know this means "register for a ticket to attend in person"?

**Comment by argyleink** [comment]
i think register is pretty self explanatory, but you simply questioning it makes me think it should be text from a CMS, aka folks may want to customize their CTA. 

curious if you think title copy would pacify a wondering user who is hovering on the button for more context? 

furthermore, per our GVC today, our implementation looks like it'll get customized to feature a live stream CTA as well. we have what chrome wants to do with that space, and what white label wants. for now, i'll pacifying chrome, but i do appreciate the poke here, as it's currently too assumptive on verbiage.

**Comment by jakearchibald** [comment]
Rolling into https://github.com/GoogleChrome/devsummit/issues/184

**Comment by argyleink** [comment]
also see #209
