### ISSUE TITLE
Add login system

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#136]
Add a login system so we can:

* Persist if the user is attending
* Remember which sessions the user is interested in
* Target content to speakers

**Comment by jakearchibald** [comment]
We'll also need to do a legal & security review for holding the data

**Comment by argyleink** [comment]
at some point I'd like to sync about this feature, and that sync i imagine is mostly a pull from me as i ramp up to the service and ui y'all've chosen. want to make sure i provide you with everything you need. right now, i dont feel very prepared to design around auth, bit of a black box atm.

**Comment by argyleink** [comment]
oh snap, just saw #161

**Comment by surma** [comment]
Currently blocked on Privacy review
