### ISSUE TITLE
Align with design of slides

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#137]
First step: Make GDS aware of the design of the site

**Comment by surma** [comment]
Waiting to hear back from @carolrivero on this one

**Comment by carolrivero** [comment]
Checked w/ GDS on this and waiting to hear back from the design team. Will keep you posted. Thanks.

**Comment by jakearchibald** [comment]
@argyleink do you have everything you need for this?

**Comment by argyleink** [comment]
the fog is lifting yes, but let's keep this task open until i've adopted elements into our modules and layouts 👍

**Comment by argyleink** [comment]
i've been making progress on this but i'm still iterating 👍 
things are looking good tho i think, will share when i'm a bit more comfy with the integration

**Comment by argyleink** [comment]
i'm comfy sharing current status, i think it's enough integration that we look like a member of the CDS && Google family

see all the comps via [the prototype](https://xd.adobe.com/view/d4b1e5c5-5854-45e9-b2e9-0dd4f3066b94-81e2/screen/3e921b2f-316b-41a6-ad95-5b147f40ed87/Home-Desktop?fullscreen)

**Comment by surma** [comment]
RIP Dino
