### ISSUE TITLE
Add Open Graph meta tags

### ISSUE THREAD

**Issue by abdonrd** [GoogleChrome/devsummit#14]
I would like to propose add Open Graph meta tags to improve the share experience in social networks, Slack, etc.

Example: [abdonrd/abdonrd.com/index.html#L45-L61](https://github.com/abdonrd/abdonrd.com/blob/develop/index.html#L45-L61)

Card validator: https://cards-dev.twitter.com/validator
Facebook Sharing Debugger: https://developers.facebook.com/tools/debug/

**Comment by AaronLayton** [comment]
Doesn't the OG fall back to Title and Description anyway?
Wouldn't this just be a case of specifying `image` / `type`

**Comment by abdonrd** [comment]
@AaronLayton depends, in Twitter for example you need to add some meta tags.

**Comment by AaronLayton** [comment]
If I remember rightly, I think the Twitter one falls back to the OG also? Would need to confirm that.

```
<!-- Title: Uses the page title -->
<meta property="og:type" content="article"><!-- (article || website) perhaps -->
<!-- URL: Uses the current page URL, set if the Canonical is different -->
<meta property="og:image" content="http://ia.media-imdb.com/images/rock.jpg" />

<!-- minimal Twitter cards, fall back to OG where needed (I think), then back to normal on page -->
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="@aerotwist" />
```

**Comment by AaronLayton** [comment]
Or if being minimal is not an issue, throw them all in as per the specs ;-)

**Comment by PaulKinlan** [comment]
sg. @paullewis can we add these.

**Comment by AaronLayton** [comment]
I will make a PR with them in
