### ISSUE TITLE
Schedule page design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#145]
should:
- handle dates
- handle multi day schedules
- handle sessions
  - multi speaker
  - single speaker
  - short sessions
  - long sessions
  - should show duration
- handle breaks
- handle meals
- have a "shown" or "past" state for entries

should:
- be great on go phone 240px
- leverage additional space on larger screens (reveal pattern?)
- should use brand colors
- should be very legible and scannable

**Comment by argyleink** [comment]
ready for review and comments:
- [feature phone schedule](https://xd.adobe.com/view/d4b1e5c5-5854-45e9-b2e9-0dd4f3066b94-81e2/)
- [desktop schedule](https://xd.adobe.com/view/d4b1e5c5-5854-45e9-b2e9-0dd4f3066b94-81e2/screen/e2300893-0e54-40e4-ada7-339f2138f3d4/Largest-Schedule)

![schedule-timestack](https://user-images.githubusercontent.com/1134620/62238278-7ff17c00-b387-11e9-98ed-9fa4ce56f111.gif)

**Comment by jakearchibald** [comment]
I really like this. I've left a comment. Something to think about: how would we highlight the current session within this?

**Comment by argyleink** [comment]
i'm thinking a 2nd ticket for this component might be nice to capture more advanced states and features? what do you think of me taking features like:
- current session
- current time
- past sessions
- sessions with stream links
- etc
and putting them into a Schedule component v2 ticket?

**Comment by argyleink** [comment]
updates:
- print button
- space for blurb
- add to calendar button

**Comment by jakearchibald** [comment]
> putting them into a Schedule component v2 ticket?

Sounds good to me!

**Comment by jakearchibald** [comment]
I'm on a stupid train, so I can't load the design right now. Do we have a way to toggle the times between SF & wherever the user is? If not, can you mock something up @argyleink.

**Comment by argyleink** [comment]
yep, i'll jump on it. 

did you imagine a global setting that would go like on the #224 page, a schedule page level toggle, or something more inline and contextual, like a time WC with a built in toggle? i could kinda see it in any of those places, but i'm curious where you initially thought it would be. 

also, have any examples by chance of time toggling? i know what you mean, but i'm curious if there's another interface you're inspired by?

**Comment by jakearchibald** [comment]
> did you imagine a global setting that would go like on the #224 page, a schedule page level toggle, or something more inline and contextual, like a time WC with a built in toggle?

I think we should offer it wherever we show schedule time. It's purpose is two-fold. One, to provide the toggle, and two, to make it clear what zone the times are in.

> also, have any examples by chance of time toggling? i know what you mean, but i'm curious if there's another interface you're inspired by?

There's https://www.formula1.com/en/racing/2019/Italy.html

<img width="496" alt="Screenshot 2019-09-06 at 10 40 16" src="https://user-images.githubusercontent.com/93594/64418371-c7f47480-d092-11e9-8da2-6287b9940792.png">

**Comment by argyleink** [comment]
nice, great question. i think it's badass that the amount of days could change based on timezone, that's how dynamic this "static site" is. the user's in control right, and if they're keepin it in their timezone, they'll wanna know that the sessions go allllll niiiiight and into the AM, just like r kelly. 

def be weird if each day had a theme or something, luckily/intelligently we're just grouping them based on time/day and not theme. 

so nah, i think it matches the IA we have. pretty neat it could split into contextually relevant groups. 

BUT, i do agree it could be tricky if they land on the site and it says 3 days. is our default the event time and not local time?
