### ISSUE TITLE
dino-xing sign update

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#148]
needs road stripes

@jakearchibald how do you want me to deliver this? in XD fine, or you want me to edit the asset in the repo?

**Comment by surma** [comment]
Yeah, XD is our source of truth.

**Comment by surma** [comment]
But feel free to also ship code if you feel like it, just let us know :)

**Comment by argyleink** [comment]
passing back, sign updated in XD!

**Comment by surma** [comment]
I wanted to do this, but I have no idea how Jake went from whatever XD outputs to what is in the code 😂

**Comment by argyleink** [comment]
you too!? ok, i thought you did that work, now we know it's jake. it's beautiful work, i can only assume he hand ported the code over and use his expertise to shave off bit that wasnt needed. masterful jake, fo real.

**Comment by jakearchibald** [comment]
Yeah, it was mostly manual. I'll pick this up tomorrow.

**Comment by jakearchibald** [comment]
Oh the 'xing' is still there. Can we drop the xing? I still feel it doesn't mean anything to many folks outside the US, and I don't think we should be sending a US-centric message.

**Comment by argyleink** [comment]
sure, low FGs
