### ISSUE TITLE
Chromium icon update

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#150]
all other icons are grey, need to find a flat version of the brand so it can match the others

**Comment by jakearchibald** [comment]
I think we might end up removing this icon. I'm not sure what it links to. See https://github.com/GoogleChrome/devsummit/issues/184

**Comment by argyleink** [comment]
i figured it'd lead to chromium open source repo or the blog
thx for commenting on this one, i've already completed it
