### ISSUE TITLE
Add Google Developers brand icon to social list

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#151]
it was added to the designs later and is now missing from the module. asset can be grabbed from the XD developer handoff link.

**Comment by jakearchibald** [comment]
Do we want this? It doesn't feel particularly related to Chrome or the web, vs say web.dev.

@surma @kosamari

**Comment by surma** [comment]
🤷‍♂ Better than the Chromium logo, but no strong opinion.

**Comment by jakearchibald** [comment]
I mean, if we need to put an icon there, the https://web.dev/ one seems like a better option. But if we don't have a good idea of what should go there, we shouldn't add something for the sake of it

**Comment by argyleink** [comment]
cool, i'm down with removing it. i dont have a good reason for it to be there, and agree web.dev should be in within consideration if we do keep Google Developers. i'd rather have less icons, and it sounds like a slippery slope if we add this one.

**Comment by argyleink** [comment]
closing this in favor of a new topic that i feel encompasses the overarching task, see #208
