### ISSUE TITLE
Add social embed branded image

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#154]
when shared via an app or social network, should have a very nice image shown that's branded and has details about the event. users should be able to glean a majority of the event details from the embed without clicking through. 

- [ ] Twitter card headers
- [ ] OpenGraph (Facebook) headers

**Comment by surma** [comment]
I’d say we should aim to have this by Aug 1, as we are going to share the website on Twitter et al a lot.

**Comment by surma** [comment]
@argyleink Can you prioritize this one? I want the page to look good on social media when registration goes live

**Comment by jakearchibald** [comment]
I'll do the template parts of it

**Comment by argyleink** [comment]
yep, i'll attack it today!

**Comment by argyleink** [comment]
help me decide:

### choice 1
![social-share-1](https://user-images.githubusercontent.com/1134620/62249072-79223380-b39e-11e9-8197-68515014f7a6.png)

### choice 2
![social-share-2](https://user-images.githubusercontent.com/1134620/62249074-79223380-b39e-11e9-85d0-fcbf3fc02a5c.png)

### choice 3
![social-share-3](https://user-images.githubusercontent.com/1134620/62249075-79baca00-b39e-11e9-9f17-4f75bb91622a.png)

### choice 4
![social-share-4](https://user-images.githubusercontent.com/1134620/62249076-79baca00-b39e-11e9-8fef-9112434a6698.png)

### choice 5
![social-share-5](https://user-images.githubusercontent.com/1134620/62249077-79baca00-b39e-11e9-9bab-76ebb9219254.png)

preview them on XD [here](https://xd.adobe.com/view/d4b1e5c5-5854-45e9-b2e9-0dd4f3066b94-81e2/screen/7b9538e4-1d63-4bea-9962-c2301836ad4a/social-share)

**Comment by jakearchibald** [comment]
I like 5, but remember these are displayed pretty small, so I think the text needs to be bigger.

Also, if we display the location, we also need to stress that the event will be livestreamed. So either add that, or lose the location altogether.

**Comment by argyleink** [comment]
i like the idea of ditching location altogether, good suggestion. also, location and some other details can be put into the meta description.

**Comment by carolrivero** [comment]
IMHO and putting myself in attendees' shoes, it would be helpful for me to know right away where the event will take place. Most (if not all) events sites, will have the location on the first page. I wouldn't want to search for it. But that's just me.

**Comment by jakearchibald** [comment]
@carolrivero we're not talking about removing it from the page, we're talking about the graphic that appears on Twitter/Facebook when the link is shared.

In general though, I'm still worried we're placing too much emphasis on attendance, and not enough on live streamers. Ideally we'd have more live streamers than in-room attendees. We should still fill the room of course, but that hasn't really been a problem in the past.

**Comment by argyleink** [comment]
#### Google IO 2019 - social embed
![Screen Shot 2019-08-02 at 3 01 59 PM](https://user-images.githubusercontent.com/1134620/62401102-a0ac0400-b536-11e9-9118-45dc5462aa6d.png)

#### CDS 2018 - social embed 😢 
![Screen Shot 2019-08-02 at 3 02 32 PM](https://user-images.githubusercontent.com/1134620/62401103-a0ac0400-b536-11e9-9599-80a4203541a6.png)

Google IO can pull of a few things we cant, like we dont have brand recognition like they do so we cant just show a logo (imo at least). but they nailed the length and content for the description:
"Google I/O 2019 returns to the Shoreline Amphitheatre May 7-9. Join us for a hands-on experience with Google’s latest product and platform innovations." i think we should follow suit, but mention streaming more. 

taking that inspo, i've updated the share images and also comped them into a lifesize and realistic embed scenario:

##### Choice 5
![Social Test Artboard - 5](https://user-images.githubusercontent.com/1134620/62402659-a6f1ae80-b53d-11e9-8937-bbb4601c23c6.png)

##### Choice 4
![Social Test Artboard - 4](https://user-images.githubusercontent.com/1134620/62402660-a6f1ae80-b53d-11e9-9e5f-b946a83a17e3.png)

##### Choice 3
![Social Test Artboard - 3](https://user-images.githubusercontent.com/1134620/62402661-a6f1ae80-b53d-11e9-9b96-f497c4e3ab0b.png)

##### Choice 2
![Social Test Artboard - 2](https://user-images.githubusercontent.com/1134620/62402662-a6f1ae80-b53d-11e9-97ca-f594e9ce4dc2.png)

##### Choice 1
![Social Test Artboard - 1](https://user-images.githubusercontent.com/1134620/62402663-a6f1ae80-b53d-11e9-848f-4036f438663a.png)

**Comment by surma** [comment]
I like 4 and 5 :D

**Comment by argyleink** [comment]
feel free to export whichever y'all like https://xd.adobe.com/spec/1340b9aa-18f7-4859-a7b2-0e098c03c114-4613/

**Comment by harleenkbatra08** [comment]
Love 4! :)

**Comment by vschupmann** [comment]
I like 4 & 5, but I like 5 a little more because the shading and dino add a boundary. #4 let's your eye wander away too easily.

**Comment by jakearchibald** [comment]
Added in https://github.com/GoogleChrome/devsummit/pull/237

**Comment by surma** [comment]
#237 landed 🎉
