### ISSUE TITLE
Hover/focus styles

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#155]
We don't have any hover or focus styles on the links etc right now. Is that something you want @argyleink?

**Comment by argyleink** [comment]
yep! i'm a big fan of those pseudo states. not a fan of "visited" though lol
this is a great task for me to do in code too 👍

**Comment by jakearchibald** [comment]
@argyleink any thoughts on this?

**Comment by argyleink** [comment]
usually i like these rules with link colors:
- hover/focus state should increase contrast
- i like it when press/active states offset top by 1px
- focus outline should be the brand color
```css
  &:focus:not(:focus-visible) { 
    outline: none;
  }
```

is that enough to delegate this task or would you prefer i make a PR? if i make a PR, i'd probably want to turn aspects of the brand color into smaller css variables so i can do math on the saturation and lightness.

**Comment by jakearchibald** [comment]
I'm happy to take a swing at this

**Comment by jakearchibald** [comment]
Added in https://github.com/GoogleChrome/devsummit/pull/237

**Comment by surma** [comment]
#237 landed
