### ISSUE TITLE
Session section

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#162]
<img width="1441" alt="Screenshot 2019-07-25 at 17 14 18" src="https://user-images.githubusercontent.com/93594/61890580-a767c500-aeff-11e9-9ee2-9409ed0a7769.png">

I'm unsure about this subject cloud diagram thing.

If all sessions touch on performance in some way, the diagram will make it look like the conference is undiverse. If 1 talk dives into accessibility, it'll show up as a tiny little circle next to a massive common topic like performance, and risks making it look like we don't care about accessibility.

@surma @kosamari Am I worrying about nothing?

Is there something else we can do here, like a collection of html/css/wasm/js logos?

**Comment by surma** [comment]
I think you have a point.

What if we just get all tags, `uniq()` them and do a bubble diagram with all bubbles the same size.

**Comment by jakearchibald** [comment]
Yeah, that could work

**Comment by surma** [comment]
Time to pull in d3 🤘

**Comment by jakearchibald** [comment]
Haha I was just looking at d3's `pack()` source to see if I could just extract the bits I need

**Comment by argyleink** [comment]
excellent question and scenario! 

here's some thoughts and reactions to y'all's proposals:
- **undiversity**: really love you pointed out how this can alienate certain topics and appear undiverse. perhaps the whole module is optional as not all conferences will have enough tags/session meta data to groupby and total. would be a sad chart if it was a huge "design" circle lol. might be nice to separate this module out anyway, someone may want to place it somewhere else and not have it directly attached to the "about sessions" section
- **logo collection**: i feel like this suffers the same pain points as subject totals, in that it could be shallow and lack diversity, therefore not delivering the intended message of "here's a high level of all the goodies you can learn." that being said, i think a logos module design ticket should be created to capture the thought. it's been a common element amongst the conf sites i research. question becomes, is this a nice to have for our white label, and therefore punted til post CDS?
- **undiversity**: what sort of thresholds do y'all feel like would need to be in place for this effect of "appearing to not have content diversity" could be remedied by? i'm feeling like, if there is at least 3 tags found across the sessions, it's worth showing the cloud? i really like how glanceable the datavis is, in that in a few seconds i can get a sense of the overall learnings from the conf. would setting a minimum prevent this module from having that undiverse vibe?
- **same size bubbles**: i could get behind this, the helps pacify the belittling or alienation of a subject that only has 1 session or so about it. the total not being reflected by size bugs me a tiny weeny bit, but maybe we can find a better d3 chart!? as long as we dont rabbit hole and bikeshed over which chart is best, i do think there's value in exploring other ways to let this high level data be glanceable. 
- **d3**: i'm interested in what freebies can get if we use d3 (hover interactions, physics and neat interactions, etc). 

this component feels like a great place to waste/spend time, but in the grand scheme is pretty low pri and nice to have. it's goal is straightforward (forest view / macro view of session subjects), and it's overall low on the FG scale for me. v1 could even be a sorted list and i'd be content. it's also a potentially exciting component to build that is leveraged as the "convince my boss" component. 🤷‍♂ i think i've said enough lolol.

**Comment by jakearchibald** [comment]
> this component feels like a great place to waste/spend time, but in the grand scheme is pretty low pri and nice to have.

Boom. I was kinda getting excited to play with this, but you're totally right, we have other priorities right now.

Tell you what, I'll push a version that just has an image of last year's audience or whatever for now.

D3 is massive, but might be tree-shakable. Or maybe I can pull out the packing algorithm and build the rest myself.

We might be able to go with different sized circles but just keep it really subtle.

**Comment by surma** [comment]
(I was _100%_ kidding about D3.) 

I do like the circle-y visual. And if we see this section as “How do I pitch my boss to let me go to this event”, I think a diagram like this could be helpful. This diagram could totally be just DOM circles, and if JS is working, we could transition to canvas and randomize the bubbles sizes?

**Comment by jakearchibald** [comment]
I had a play with d3 and the results aren't particularly great, so I'm not sure it's worth pulling the algorithm out

**Comment by jakearchibald** [comment]
https://static-misc-2.glitch.me/d3-demo/
