### ISSUE TITLE
Nicer text selection color?

### ISSUE THREAD

**Issue by surma** [GoogleChrome/devsummit#164]
Just an idea :)

<img width="884" alt="Screen Shot 2019-07-26 at 12 05 31" src="https://user-images.githubusercontent.com/234957/61947670-b9984080-af9d-11e9-99ac-e9fd559680bf.png">

**Comment by argyleink** [comment]
nah, love this, shows a really nice layer of polish. thanks for tracking the design request!

sidenote: member html5 rocks and the hotpink text selection color that no one ever remembered to change? good times.
