### ISSUE TITLE
Jagged Line With SVG In Chrome For Diagonal Header Bar

### ISSUE THREAD

**Issue by DiestelkampA** [GoogleChrome/devsummit#17]
It seems like the svg at the top of the page used to make the diagonal effect for the header is a bit jagged in Chrome.  From what I can tell this is more visible on screen with lower pixel density... (I notice it on my lower quality laptop screen and not on a mobile device.)  It also seems to be a thing Chrome, since it shows up fine in Firefox and Edge.  I'll try to include some screenshots below, though it may be hard to see from that.  Are there any tricks that could be used to make SVG render more smooth in Chrome?

Chrome: 
![image](https://cloud.githubusercontent.com/assets/5522019/19698111/95c6f572-9ab3-11e6-8664-284731dc1905.png)

Firefox:
![image](https://cloud.githubusercontent.com/assets/5522019/19698072/74744136-9ab3-11e6-8119-1047039be529.png)

Edge: (shadow doesn't render correctly in Edge as well...)
![image](https://cloud.githubusercontent.com/assets/5522019/19698046/5d942a1c-9ab3-11e6-8b72-e68eb901eed7.png)

**Comment by surma** [comment]
I don’t think we have any control over how Chrome renders SVG. But I might turn this into a [Chrome Bug](https://crbug.com) once CDS insanity is over :)

**Comment by paullewis** [comment]
Pretty much, it's down to the browsers and there isn't much I can do. Going to close it for now.

**Comment by DiestelkampA** [comment]
Alright, fair enough. Might seem like splitting hairs.  If you are viewing it on your high pixel density laptop display I doubt you can see much of an issue. 

For what it's worth my colleagues immediately asked about it when I showed them the site as well...  The jaggedness looks bad enough that it almost looks like the material design tab underline thing under the various section in the header...  I guess there are lot of known issues when it comes to Chrome and rendering svg consistently that I see a lot people complaining on stack-overflow about.
