### ISSUE TITLE
Add blurry image thing for loading images

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#170]
We could add an 11ty tag that handles this plus aspect ratio fixes

**Comment by argyleink** [comment]
could use backdrop filter on tiny tiny images covering the image loading space?

**Comment by jakearchibald** [comment]
What would the backdrop filter do?

**Comment by argyleink** [comment]
blur the LQIP while a HQ image loads. i guess filter blur() works as well
would make a great case study if you can architect a solution here that outdoes Gatsby's

**Comment by surma** [comment]
Upscaling a low-resolution image (4x4 or something) will naturally be blurred, so we don’t need another `blur()` on top :)

**Comment by jakearchibald** [comment]
To speed up discussions like this, it's best to address them in terms of the goal sought, rather than the possible technologies.

Eg:

> We should use lodash here

vs

> We should ensure this set of items is unique

With the former, it's unclear what we'd use lodash for, since it can do many things.  Whereas the latter addresses the goal directly. Then, if there's consensus around that goal, we can figure out which technologies can be used to achieve it.

**Comment by argyleink** [comment]
oh, figured the goal was clear (blurry image thing) and we were onto strategies/tactics 🤷‍♂ 

i do like blurring a 4x4 to smoothen it's blur, but y'all can veto that. pixelated could be our niche.

**Comment by surma** [comment]
It's not pixelated by default. It's blurred. Upscaling in chrome uses bilinear (I think) by default.  You have actively opt in to pixelated with `image-rendering: pixelated`

**Comment by jakearchibald** [comment]
> oh, figured the goal was clear (blurry image thing) and we were onto strategies/tactics

Sure, but it wasn't clear what a backdrop filter added to regular image scaling until you said:

> i do like blurring a 4x4 to smoothen it's blur

**Comment by argyleink** [comment]
woh cool, wonder why i've always additionally blurred. guess i need to go look closer at what the browser does be default. maybe i blurred before even looking.
