### ISSUE TITLE
chrome://community guidelines

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#183]
https://cds2019-d4673.firebaseapp.com/coc/

Does this break the URL-ness of the title? We could easily slugify it to `chrome://community-guidelines`.

@argyleink @surma

**Comment by surma** [comment]
I was thinking about that too, but I figured it wasn’t a trivial CSS transform and if we change the actual text screen readers might butcher it? We could `aria-label` it, I guess? Not sure. No strong opinions.

**Comment by argyleink** [comment]
"no strong opinions" is a PC way of saying "low on the FG scale" lol, well done, i remember that when i'm filtering

i vote slugify, as it's an ode to chrome settings and it's a dev conf about web

i love surma's thinking about screen reader ux so much 👍 in this case, reading the "-" outloud sounds kinda "on brand" lol, in that it's nice screen readers wont miss out on the play. 

do screenreaders read the pseudo content too? like "chrome. colon. slash. slash. ...?" if the do, that sounds a bit annoying.

**Comment by surma** [comment]
The `chrome://` is a pseudo element, so it won’t be read out loud. 

RESOLVED: slugify :)

**Comment by argyleink** [comment]
![image](https://user-images.githubusercontent.com/1134620/62141652-cd93b900-b2a1-11e9-8923-d0f740be07b9.png)
