### ISSUE TITLE
Add to calendar links

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#186]
I think this should be an ics feed, as it's something that can be subscribed to and update over time.

For launch it'll just be a single two day event, but we'll plug this into our session data so it expands into session-by-session info for anyone subscribed.

https://www.addevent.com/add-to-calendar-button might be an interesting thing to use as inspiration.

We might need some design work here.

**Comment by surma** [comment]
Fiddling with this

**Comment by surma** [comment]
Prototype on the `ical` branch. Waiting to hear from the Google Calendar team on how to generate ical links.

**Comment by jakearchibald** [comment]
On https://www.formula1.com/en/racing/2019/Hungary.html, the "add to calendar" link uses the direct ical link for Apple & iOS, and for Google Calendar: `https://calendar.google.com/calendar/r?cid=[full link to ical]`.

Lol wait `https://calendar.google.com/calendar/r?cid=https://ical--cds2019.netlify.com/devsummit/fullevent.ics` doesn't work, but if you change the `cid=https` to `cid=http` or `cid=webcal` it *does* work. Amazing.

What isn't clear to me is which will auto update. I'll keep experimenting with that.

@argyleink the "add to calendar" link: we can either make it go to another page where the user is given Apple/Google/Outlook options, or we could do it in a little popup. Any preference?

**Comment by argyleink** [comment]
![Screen Shot 2019-08-02 at 11 26 00 AM](https://user-images.githubusercontent.com/1134620/62390938-5ddb3380-b518-11e9-8f4b-59566e34114d.png)

i'm not a fan of modals.. i'm happy to put this functionality into an input with a <datalist> or <select> with <options> matching our options (apple/google/etc). then when the user invokes our button, we can present them with native ui. this is especially handy on mobile. on input, trigger add to calendar flow. 

maybe this button is reuseable for session detail also? do we want to let folks put single sessions on their calendar? v2 feature?

**Comment by jakearchibald** [comment]
> i'm happy to put this functionality into a .01 transparency input with a `<datalist>` or `<select>` with `<options>` matching our options (apple/google/etc) that's overlayed on the calendar link. then when the user invokes our link, we can present them with system picker. this is especially handy on mobile. on input, trigger add to calendar flow.

Isn't that also uncanny? It's unusual for selecting a select to result in an action. I worry situations where the options are 'changed' as the user scrolls through them. Also, with this pattern, it's difficult to share links.

Maybe a separate page with links is better for now. I agree that overlays are ugh.

> maybe this button is reuseable for session detail also? do we want to let folks put single sessions on their calendar? v2 feature?

That would be easy to do. I worry about giving the user too many options, but maybe it's fine.

> also, can web share help us here in a progressive enhancement way?

Not that I can think of, but it's early here. Can you explain a bit?

**Comment by argyleink** [comment]
uncanny? i see your point, but i feel like the examples linked were "uncanny" in the same way: a "button" reveals a tiny select-like overlay, that when an item is picked, no state is updated but the choice results in a fired action. looks like you shared the same UX as a good example, but don't like the use of a select box? i'm a big fan of using the select box, it's solves so many issues across platforms and browsers that I dont want to deal with. but, do agree it's a bit odd that we ask users to make the selection but dont really persist it. 

i feel like a separate page would be fine, but what's on that page, 3 links? sounds more like a card than a page. maybe we shouldnt have an add to calendar button, we have an add to calendar widget that doesnt require any links/buttons to be "revealed"? **do we have an audit of what calendars we support yet?**

web share, to help illustrate how i feel this is progressive enhancement, lemme bullet out the ux i see for this interaction, assuming we choose the select box option:
- user clicks "add to calendar" button from mobile or desktop
- ui presents: "google" "apple" "outlook" "copy link" "web share (if supported)"
- on mobile, this results in a full screen native picker on android, or the badly aging rolodex wheel on ios, but nonetheless it's very familiar UI to the user, and they are able to quick assess which option they'd like without distraction
- user #1 chooses google, which our javascript gets the oninput event and instructs chrome to open a new tab with the google calendar link as the destination, kicking off a native workflow
- user #2 choose web share, which our javascript kicks off the native share intent with the google calendar url as the src. the user now sees the native share sheet and can choose an app that has intent handlers for calendar urls (i'm assuming share intent can distinguish or has utils for event links)

so what i like about web share here is that it's meaningful: we're letting the system show the user what apps are prepared to handle event intents. in the long run, would allow us to not show "apple" to a user on an android. this box with a model or whatever is pretty much exactly what web share is gearing up to replace. we wouldnt have to maintain multiple link strategies! 

lastly, cuz this is getting long, i like the select box strategy, even though i suppose the result of your interaction with it could be uncanny (i made a selection then couldnt see it in a form), i think the rest of the UX around the decision and presentation are very close to home and will be the best match for the form factor of the interaction: super nice that mobile users will get native and mobile centric ux. our feature phones, i imagine the cursor support on a select box is pretty familiar and nice.

**Comment by jakearchibald** [comment]
> uncanny? i see your point, but i feel like the examples linked were "uncanny" in the same way

That's why I said "also uncanny" 😀

> i'm a big fan of using the select box, it's solves so many issues across platforms and browsers that I dont want to deal with

But it *creates* cross-platform issues too, like the selecting-while-scrolling thing I mentioned. Take this reduced example: https://jsbin.com/povoxac/. Let's say you are a keyboard user, and you wanted to select option 3. 

On mac, you tab onto the input, press down, the select opens, you continue to press down until the required option is highlighted, you press enter, and the "change" event is fired and the page's JavaScript reacts.

On Windows, you tab into the input, press down, and now you've selected 1. The "change" event is fired and the page's JavaScript reacts. You press down again, and now you've selected 2. The "change" event is fired and the page's JavaScript reacts. Etc etc.

If our JavaScript reaction is to navigate to a particular calendar URL, keyboard users on Windows will not be able to select anything other than the first item.

This is why it's generally bad to use `<select>` for navigation.

> maybe we shouldnt have an add to calendar button, we have an add to calendar widget that doesnt require any links/buttons to be "revealed"? do we have an audit of what calendars we support yet?

That feels like a good idea. I think we only need to support iOS, Google Calendar, and Outlook. We could use icons for that.

> web share, to help illustrate how i feel this is progressive enhancement, lemme bullet out the ux i see for this interaction

Ohh interesting! I guess we wouldn't call it "web share", but something like "other app". It could be worth an experiment, but which users are benefiting? I guess it's users that are using a web share capable browser, and are wanting to target a calendar app that isn't iCal/Gcal/Outlook, and that app does the right thing when icalendar URLs are shared to it. It feels a bit small.

**Comment by argyleink** [comment]
great demo and ux walk through to help me ramp up to that ux issue. i completely agree that the `oninput` event is the wrong event. therefore, let's use `onblur`... JK! lol, `<select>` is dead to me now. not only were we not displaying it's state and using it, we're also ruining a keyboard users ability to pick state without eagerly triggering selection. nice jake! <3

will explore more interaction patterns for this, want to find something minimal and inline. 

web share, let's punt it to the pile of "nice to have chrome showoff features" that we can pluck from when we've got extra cycles? def feels like the way to "add to calendar," but from the future. LIVE IN THE NOW!

![image](https://user-images.githubusercontent.com/1134620/62491508-fc69cd80-b780-11e9-8972-3ed99d4f6bdd.png)

**Comment by argyleink** [comment]
![IMG_20190805_155246](https://user-images.githubusercontent.com/1134620/62499978-668e6c80-b799-11e9-953b-c5c97233d7e0.jpg)

spent 30m sketching up some ideas, thoughts? here's a brief on each, in case it's not obvious:

##### Split Button
- separates action to add to calendar from selection of service
- selection of service should persist throughout other instances
- i imagine a `<select>` handling the service choice, and a regular button handling the add behavior

##### Natural Language Link
- even slimmer version of the split button, like a split link
- both link and `<select>` can be in their natural presentation style
- still get the value of a split button without the "component"

##### Card Widget
- meh, fine, just bulky
- fits a story where we send users to a venue detail page and then this bigger bolder UI can be present

##### Expanded
- unpack even more, hide nothing, tuck integration into tiny links

##### No Choice
- UI shows only 1 button, matches the current design, and under the hood we made the decision for the user based on the device they're visiting from

tradeoffs all around! what say you?

**Comment by argyleink** [comment]
i'm leaning towards natural language link with select https://codepen.io/argyleink/pen/NQyxQM

**Comment by vschupmann** [comment]
FWIW - I like the natural language link the best.

**Comment by jakearchibald** [comment]
I'm not sure about the interaction of the natural language link.

Add to [ Google ⌄ ] calendar

I assume, at this point, if the user clicks "Add to" or "calendar", they'd be taken to Google Calendar to add the event. That seems fine.

However, if they click "Google", a drop down will appear, and if they pick "Google", nothing will happen. That seems odd.

If they click "Google", and select "Apple" from the drop down, we *could* make something happen here, but we shouldn't due to the problems described in https://github.com/GoogleChrome/devsummit/issues/186#issuecomment-518304052. So, the use would have to select "Apple", then click on either "Add to" or "calendar". That's three taps, and I worry that users would stop after the second expecting the interaction to be complete.

The split button is nice and compact, and, as long as we don't use `<select>`, would allow the interaction to be two taps. We just need to make sure it's clear that options will appear on tap, instead of only offering Google Calendar or whatever the initial option is.

**Comment by surma** [comment]
I'll leave this up to y'all, but my 2 cents would be: We need to support 3 calendars or something? And it's not like we are tight on space. My vote goes to just listing the names and/or logos next to each other.

**Comment by argyleink** [comment]
nice feedback!

1. i thought we had agreed that select menus should never trigger an event after selection? 
2. it's only 3 taps if it's your first interaction with the button and the default choice isnt what you want. otherwise it's 1 click/tap. component should remember users choice and set the proper default option on page load/render when known. 
3. see the codepen, yes, the user can click on "add to" or "calendar" because they're the same element and are the same normal link. keyboard usage of this component works great as is. 
4. now that we have a user settings page, we could put a dropdown there where they pick their calendar choice? see the (no choice) option in the sketch, which tries to make it's best assumption on the calendar type based on user agent. maybe our button reads the UA unless it's been told via a session setting that the user wants a different calendar? 
5. split button also should remember the choice, so becomes 1 tap after calendar is chosen

my biggest concern is anything that requires a click to show the options as an overlay: we'll need to build some roving tab handling, focus, etc. i'm trying to help us not do a bunch of a11y work. if the split button looks easy, i'm happy to design that one further. lemme know!

**Comment by jakearchibald** [comment]
> i thought we had agreed that select menus should never trigger an event after selection?

Native select menus shouldn't, due to the interaction issues I covered in the thread. But nothing happening after clicking [Apple logo] seems bad too, right? Won't mouse users expect something to happen?

> it's only 3 taps if it's your first interaction with the button and the default choice isnt what you want. otherwise it's 1 click/tap. component should remember users choice and set the proper default option on page load/render when known.

I don't think we should optimise for repeat actions here. It isn't something we'd expect the user to use lots, right?

> see the codepen, yes, the user can click on "add to" or "calendar" because they're the same element and are the same normal link. keyboard usage of this component works great as is.

But mouse usage is broken. I'm not convinced about keyboard use here either.

> make it's best assumption on the calendar type based on user agent

I'm not sure we can do that. Eg, what's the guess for a Windows Edge user? Is it Outlook? Google Calendar?

> my biggest concern is anything that requires a click to show the options as an overlay: we'll need to build some roving tab handling, focus, etc. i'm trying to help us not do a bunch of a11y work.

I think we should start by figuring out the best experience for users, then figure out the best technology to deliver that experience. If we need to make compromises, we can look at that, but we shouldn't do that until we've aimed for the best experience.

**Comment by jakearchibald** [comment]
Since we couldn't get consensus on the calendar layout, I'm going to drop it from the 20th launch. We can add it back as soon as we figure out the interaction.

**Comment by argyleink** [comment]
i'm leaning towards the middle option above

**Comment by surma** [comment]
> My vote goes to just listing the names and/or logos next to each other.

😅 #calledIt

Bottom 2 options work well imo.

**Comment by argyleink** [comment]
you did!

i like how we kinda over-designed/engineered it at first, then dialed back, dialed back, and found a clean, highly usable solution that isn't clever. thread here shows the process, kinda neat tbh. makes me wish i hadnt over-thought it from the beginning!

**Comment by jakearchibald** [comment]
Excellent. Let's go for the "Add to: [list of options]" version.

I think we should call it "Apple" rather than "iCal". It isn't called "iCal" on iPhone.

**Comment by argyleink** [comment]
comps updated 👍

**Comment by surma** [comment]
@jakearchibald I updated the calendar links on the `ical` branch, but the links are now on the schedule page, so I’ll wait for that to land.

**Comment by surma** [comment]
I just stumbled over the `add-to-cal` include that’s on the `session-page` branch. Not gonna do anything about that for now, but this needs to be reconciled eventually.
