### ISSUE TITLE
Some contrast ratios are not passing

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#196]
![Screen Shot 2019-07-30 at 8 38 49 AM](https://user-images.githubusercontent.com/1134620/62144346-7e03bc00-b2a6-11e9-811c-ada2e506a686.png)
![Screen Shot 2019-07-30 at 8 39 02 AM](https://user-images.githubusercontent.com/1134620/62144347-7e03bc00-b2a6-11e9-9dca-a1c862472f6c.png)
![Screen Shot 2019-07-30 at 8 39 08 AM](https://user-images.githubusercontent.com/1134620/62144348-7e03bc00-b2a6-11e9-9d1e-163f3c953eaf.png)

**Comment by surma** [comment]
Adam is OOO, so we won’t fix this for initial launch.
