### ISSUE TITLE
Middle click to open link in new tab is not working (same for right click)

### ISSUE THREAD

**Issue by frigus02** [GoogleChrome/devsummit#20]
It's not possible to open a link in a new tab by clicking on the mouse wheel (something I do quite often), because all click events are being prevented. I can see, that there is already a [check for ctrl or meta key](https://github.com/GoogleChrome/devsummit/blob/06f49a0b238f354d1fd493cf161972e6c7078058/scripts/cds.js#L298). I guess it would make sense to also filter for [left clicks](https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button) like so:

```
if (evt.metaKey || evt.ctrlKey || evt.button !== 0) {
  return;
}
```

What do you think?

**Comment by surma** [comment]
The point of capturing clicks is so that we can take over navigation because of our SPA routing. So 

Checking for middle mouse seems like a good idea. You wanna submit a PR? 😉
