### ISSUE TITLE
Deploying

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#201]
@samthor do you know how https://developer.chrome.com/devsummit/ is configured? As in, how would we point it at a Firebase project?

**Comment by surma** [comment]
I’m on this

**Comment by samthor** [comment]
App Engine chromedevsummit-site.

I can give y'all access if you don't have it.

**Comment by surma** [comment]
I have access. Thanks Sam!

**Comment by surma** [comment]
I have _a_ solution. Closing this.
