### ISSUE TITLE
Replace register button in header with switch to indicate attending vs streaming

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#209]
**requirements:**
- streaming is default
- switch should not get visual treatments that make one look better than the other
- switching to "attending" triggers a user question (prompt? modal?) to ask if they want to register (note: question should only show once per device)
  - if yes: nav user the registration page
  - if no: adapt page to new "attending" state
- switch should have state that knows if a user registered or not (as good as it can) on each page load, striving to reflect attending/streaming state
- switch should not be the only way for the user to specify they're attending

**Comment by argyleink** [comment]
![stream vs attend](https://user-images.githubusercontent.com/1134620/62331332-7db71c80-b470-11e9-8875-4b98ad92a010.png)

here's a couple switch ideas, thoughts?

**Comment by jakearchibald** [comment]
If there some way we can stress that this is just a 'view'. Eg, we don't want users to think that deselecting 'attending' cancels their ticket.

**Comment by surma** [comment]
I definitely prefer the version where you can see what both states mean. The just-icon version does not seem self-explanatory enough for me.

I wonder if we should _not_ put that switch in the header but maybe on a dedicated user page, where we can put an explanation around it?

**Comment by argyleink** [comment]
i'm def feeling like having this button prompt any realities around registration is overloading it's UX, good call. 

i think the idea of this just changing the view and not having anything to do with actual attendance, is best. i would prefer this button is very **inconsequential to play with**, so folks can flip it on and off without repercussion.

i suppose the less we try and manage any state around attendance within our site is best, aka punting as much to the registration service to manage that state is best. curious though about auth, and if we want to show a dedicated user page? maybe it's a nice to have? where should we put links to where folks can manage their attendance and apply? FAQ perhaps?

**Comment by argyleink** [comment]
i'm going to investigate new areas for toggling attending state. i dont think the header nav is the right place, it's much more standard to have a registration cta there, not an attendance state toggle. we can though use the attendance state to potentially change the cta. TBD

**Comment by jakearchibald** [comment]
Could be resolved by https://github.com/GoogleChrome/devsummit/issues/212#issuecomment-519487457

**Comment by argyleink** [comment]
i feel like this is resolved by #224, #212 has some great conversation pieces on it.
