### ISSUE TITLE
Session datavis

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#211]
things to be conscious about with this component:
- folks might not like or be aware of their high level session tally, and this tally could make them appear counter to their goals, aka no counting
- avoid making 1 subject look better than another, no stack ranking or comparisons
- should deduce for feature phones, but expand and consume more visual space on desktop

**Comment by argyleink** [comment]
![Screen Shot 2019-08-07 at 1 32 13 PM](https://user-images.githubusercontent.com/1134620/62655867-ce6ac180-b917-11e9-9396-d9127068962c.png)

**Comment by jakearchibald** [comment]
Ohhh I like this. Nice one!

**Comment by argyleink** [comment]
whoever design this must not like CSS, it's last which means it's shite 😂

**Comment by argyleink** [comment]
i remember surma mentioning somewhere that 11ty is prepared to make filtered views of the sessions? that mean we can have these labels/tags/whatevers be links?
