### ISSUE TITLE
Responsive navbar

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#213]
current designs leave much to be desired:
- desktop
  - no hover
  - hover, active
  - hover over child item
  - current nav item (matches route)
  - define breakpoints
  - touch support?
  - conditional cta
  - session state
- mobile
  - define breakpoints
  - session state
  - current nav item (matches route)

**Comment by argyleink** [comment]
as i iterate on this it's being simplified 👍

**Comment by argyleink** [comment]
thoughts? what did i miss? there more states y'all would like to see covered? 

##### Desktop
![Desktop  Nav](https://user-images.githubusercontent.com/1134620/62981346-d75b0780-bddd-11e9-834d-37b93c50e75b.png)

##### Mobile
![Mobile  Nav](https://user-images.githubusercontent.com/1134620/62981348-d75b0780-bddd-11e9-8943-8bd72165c982.png)

fixes #142

**Comment by jakearchibald** [comment]
These are great!

**Comment by surma** [comment]
+1, loving these. Gonna tackle these once we have the login infra landed, so post initial launch.

**Comment by jakearchibald** [comment]
fwiw I did the hover states in #237.

**Comment by jakearchibald** [comment]
Issue for the next phase: https://github.com/GoogleChrome/devsummit/issues/254
