### ISSUE TITLE
Cookie prompt

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#214]
will we be using cookies? does design need to provide any comps for handling the cookie prompt?

**Comment by jakearchibald** [comment]
We should ask privacy, but the current site *doesn't* have this.

**Comment by argyleink** [comment]
can i lean on you to find the answer to this? if last years site is any kind of indicator, sounds like we're in the clear, but perhaps things have changed.

**Comment by jakearchibald** [comment]
It'll fall out of the privacy review as part of the login work @surma is doing.
