### ISSUE TITLE
Live stream content block

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#215]
module to callout streaming

**Comment by argyleink** [comment]
Copy can change, but idea here is to drive folks to youtube to hit "subscribe" or "get notified". Should be a portable module that we can place around. 

currently, the mobile module, fully fits within the viewport on a feature phone 👍 

![Stream Module](https://user-images.githubusercontent.com/1134620/63549687-c6994880-c4e5-11e9-9995-90e05752dd6c.png)

**Comment by jakearchibald** [comment]
Nice. Where do you see this being used? On the homepage and/or session pages?

**Comment by vschupmann** [comment]
Yes!  And I'd like to see this on the Attending page (and/or Venue page).

**Comment by argyleink** [comment]
you'll find it scattered across comps already. i tended to put it places where folks would be hitting a dead end since they're not attending (end of schedule page, end of FAQ, etc)
