### ISSUE TITLE
Attendee party module

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#216]
not a crazy module, but would be nice to centralize the details

**Comment by jakearchibald** [comment]
I wonder if this is just a type of 'session' except:

* No speakers (unless there's some kind of afterparty performance).
* Marked as 'attendee only', so it doesn't appear in the session index.
* Has a location (although, in multi-track events, all sessions will have a location).

**Comment by argyleink** [comment]
schedule design already has accommodations for parties with links to maps n stuff. this is in case marketing wants to put information about the party other places, like the home page, the venue page, etc. Some sort of party content block just about parties. 

**hmm, maybe we could knock out a few birds with 1 stone:** 🐦 🐦 🗻 
what if we made a module that could filter the sessions collection and use that filtered set in this module to promote them? then 1 module could show parties, all sessions of a category, etc. We'd essentially liberate users of this conf tool to build their own content blocks based on what they feel is important. thoughts? 

i marked it as nice to have, but didnt put it into the project. figure it's still a question.

**Comment by jakearchibald** [comment]
Yeah, I like the idea of tagging session items so rendering can be controlled. Whether we offer filters to the user is another question. We'd definitely want that for I/O.

**Comment by surma** [comment]
This is now needed by Sep 20

**Comment by argyleink** [comment]
i'm struggling to filter out the noise in the content docs around this party module. is it needed by sep 20 still, or did it get punted? from what i can tell, it's punted, but I dont want to leave this task hanging if other's are expecting it. 

seems like the minimal ask is: a module that can show a party time/place/date?
seems like the ultimate ask is: a module that can show any session(s)/event(s) based on params?

**Comment by jakearchibald** [comment]
Ping @surma: Is this still needed for Sept 20? What was the reasoning? Is an entry in the schedule sufficient?
