### ISSUE TITLE
Session detail page design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#217]
should
- include all session details expanded
- have a speaker(s) summary module teasing speaker full page
- link to slides
- be the stream
- feature this ux https://samdutton.github.io/transcripter/lK3OiJvwgSc.html
- nice to have: next/prev session buttons
- CTA to buy tickets/register

**Comment by jakearchibald** [comment]
Always:

* include all session details expanded
* have a speaker(s) detail module

Before the event:

* Module to buy tickets/register

Before and during the event:

* A way to 'star' this session and get notifications
* nice to have: next/prev session buttons (in schedule order, if there's a schedule)
* nice to have: Also on at this time (if there's a schedule available, and it's a multi-track conference)

During the session:

* "Live now!" link to livestream

After the event:

* Video if available
* Links to assets if available

**Comment by jakearchibald** [comment]
@argyleink any chance of doing this in the next few days? We only need the 'always' and 'before the event' states for the 20th launch.

**Comment by argyleink** [comment]
good timing, v1 is ready to review, so we can squeeze an iteration in if we want. i struggled with this page, it has the most turnover and iteration than any other. curious whatcha think. 

<br>

<details>
  <summary>Desktop v0.0.1</summary>
  
![Desktop - Session](https://user-images.githubusercontent.com/1134620/64356846-61028d00-cfb8-11e9-9d74-2786721711c2.png)

</details>

<details>
  <summary>Mobile v0.0.1</summary>

  
![Feature Phone – Session](https://user-images.githubusercontent.com/1134620/64356869-695ac800-cfb8-11e9-9907-98242426f43d.png)


</details>

**Comment by vschupmann** [comment]
FYI - I'll be looking at limiting the titles to 75 characters max.  This is a good thing on all levels, but it is a requirement for YouTube.

**Comment by jakearchibald** [comment]
@argyleink what do you think about moving the date/time/cal bit to the space in the right-hand side of the title? No need to comp it if you're pushed for time. We can just do it.

We should also have a way to toggle time between event time and user's time.

**Comment by argyleink** [comment]
good call, details to the right of the title look great 👍 
working on timezone toggle in #261 💀 🤘 

<br>

<details>
  <summary>Desktop v0.0.2</summary>
  
![Desktop - Session](https://user-images.githubusercontent.com/1134620/64444699-9e831b00-d089-11e9-8ba3-3da6cd461c19.png)

</details>

<details>
  <summary>Mobile v0.0.2</summary>

![Feature Phone – Session](https://user-images.githubusercontent.com/1134620/64444702-a17e0b80-d089-11e9-9b4f-9236e1595509.png)

</details>

**Comment by surma** [comment]
@argyleink What is the difference between the left lorem ipsum and the right lorem ipsum in the desktop view? Is the right one the transcript? Or the long abstract? (I don’t think we will have short and long abstract. Just one paragraph per talk or something)

**Comment by argyleink** [comment]
idea for the left lorem area was:
1. spot for any session meta embellishments about the team/duo/talk/demo/short/tldr abstract/etc
2. follows the design patterns from the rest of the pages, so was a consistency thing and an overflow space in case content authors needed it

notice how it's not in the mobile comp (the left lorem area), and that's because it's superfluous/meta content that's not critical. great candidate for an if/else content block, if we have it great, if we dont, no biggie. 

the right lorem area was for the long abstract / session description

that help? i made it sound like we dont need it lol, which maybe we dont. i'll chat with content folks to see if it's a useful space or it's unneeded.
