### ISSUE TITLE
Speaker detail module

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#218]
should
- show all speaker(s) details expanded (name, company, company role, social links, img, bio)
- gracefully handle multiple speakers
- have a simple link to session(s)

**Comment by jakearchibald** [comment]
Could this just be a module that goes on the session page?

**Comment by argyleink** [comment]
in my current design IA, a session page already has a summary module about the speaker(s) with link(s) to their pages, and vice versa, where a speaker page has a summary module with link(s) to the session(s) they're in. i considered merging them too, but felt that leaf/detail pages for each collection item would scale more to the various speaker/session combos out there. thoughts?

**Comment by argyleink** [comment]
i also think it's really nice for a speaker to have a dedicated page to share, that's not just about their session(s). also, if a session has multiple speakers, it's a nice gesture to give them each their own detail pages instead of making them merge their notes about themselves or something.

**Comment by argyleink** [comment]
portable as a module, no need for dedicated pages if we have dedicated sessions 👍 
updated the description with some updated expectations

**Comment by argyleink** [comment]
i'm thinking now we skip this page entirely and link any "profile clicks" to the respective profile on chrome developers, or some other entity where our bios already exist. thoughts?
