### ISSUE TITLE
Venue page design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#219]
should
- provide written directions regarding coming from airport, train, etc
- provide a link to google directions
- show a map (static or dynamic?)
- history / about regarding the venue?
- near hotels?

**Comment by jakearchibald** [comment]
> (static or dynamic?)

I think it should only be dynamic if we can think of a reason that benefits the user. I think a link to Google Maps is enough.

> history / about regarding the venue?

If we have some general content styles (that cover headings, lists, floated images, full images) then we can use those for content like this, if we need it. Avoids doubling up on the work.

**Comment by argyleink** [comment]
agree on static for the map, i'll provide the static image. dynamic isnt very useful and is a gorilla on the page.

**Comment by argyleink** [comment]
Decided to limit some of the scope of this page with the reasoning that things like hotels, sights, history, etc is all Googleable. No reason we need to go compile all that when folks can query for exactly what they want. 

Thoughts?

**note**:
- nav hover state is wrong (meh, dont feel a need to fix it)
- map background color is wrong
- copy can/should change
- will finish mobile comp soon
- links with arrow north-east indicate an outbound link (like this pattern?)

#### Desktop v0.0.1
![desktop-venue](https://user-images.githubusercontent.com/1134620/63556202-ba6ab680-c4f8-11e9-8317-c7b37c439229.png)

**Comment by vschupmann** [comment]
There are a few items that could be beneficial on this page:

- Tips about lost & found, meals provided, info about the after-hours party, parking, bike racks

- Hours/badges/badge pick-up, etc.

- Accessibility accommodations

- Niche attendance info about minors, solicitation rules 

- We provide mothers rooms - prayer rooms - 

- Women Techmakers

**Comment by vschupmann** [comment]
Also, I think Venue could be a good umbrella term for what goes on this page. Nobody else uses that but there's no reason that we should not use it!  Other conference/summit sites use "Attending" and "Location" and "Logistics" for this info.

**Comment by vschupmann** [comment]
> - Do you have any of this/these in long form, or just the summarized idea of the content?

I'm pulling together some thoughts in [Jake's content plan](https://cds2019-d4673.firebaseapp.com/ ). It is not complete because we are waiting for input from the marketing company we work with for this venue.  I'm happy to move this data to GH or to another place. Just let me know. 

> - Which of these items could live on FAQ instead of venue?

Parking, bike parking, meals, mothers room, prayer room, etc. are in the FAQ now. 
Q: Where is the best place for these items?


> - OR, how much of this "venue" information can we punt/lean onto to the actual venue site instead of managing it ourselves? maybe we write a little blurb that explains if folks need rich venue information they should visit the venue site itself, so we can shed ourselves of that content responsibility?

I'm very interested in working with you to reduce the content size where possible. I think you are still fresh to this website and could bring a nice outside view. Suggestions are welcome.

**Comment by vschupmann** [comment]
Hotels 

Adam, our email alias -chrome-dev-summit@- gets a lot of requests for info on nearby hotels so I'm providing this list that we published on the website last year. Please don't publish for 2019 until I verify with GPJ. 

St. Regis San Francisco 
Address: 125 3rd St, San Francisco 
Number: 415-284-4000
Distance to YBCA: .1 Miles
Directions, <click here> 

W San Francisco
Address: 181 3rd Street, San Francisco
Number: 415-777-2000
Distance to YBCA: 433 Feet
Directions, <click here> 

Four Seasons Hotel
Address: 757 Market Street, San Francisco 
Number: 415-633-3000
Distance to SF Jazz: .3 Miles
Directions, <click here> 

San Francisco Marriott Marquis
Address: 780 Mission Street, San Francisco 
Number: 415-896-1600
Distance to YBCA: .3 Miles
Directions, <click here>

**Comment by jakearchibald** [comment]
@argyleink whoa, the integration of the map into the design is great!

**Comment by vschupmann** [comment]
Is this staged somewhere?

**Comment by argyleink** [comment]
**changelog:**
- no more unlicensed photos of YBCA
- macro map now has a helpful micro map just under it, felt like just seeing the surrounding streets is super valuable
- added an indoor map too, for an even MOAR micro view to the space/venue
- added "additional information" (needs better section title?) upon request
- has new branding divider inbetween footer and stream module

**note:** mobile comp not updated yet

<br>

<details>
 <summary>Desktop v0.0.3</summary>
 
  
![Desktop - Venue](https://user-images.githubusercontent.com/1134620/65287031-78806080-daf6-11e9-9ac2-41f71a0309f2.png)


</details>
