### ISSUE TITLE
Countdown widget

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#220]
![Screen Shot 2019-08-06 at 8 32 39 PM](https://user-images.githubusercontent.com/1134620/62592857-9157ee00-b889-11e9-9f02-b931697bc4f5.png)

vote by reacting 👍 or 👎

**Comment by jakearchibald** [comment]
Yeah, I like the idea of this being a homepage module. Maybe it's part of the module that presents the live stream, since it'd be replaced with the livestream when the counter reaches 0.

**Comment by argyleink** [comment]
![countdown](https://user-images.githubusercontent.com/1134620/67129316-2e50d480-f1b3-11e9-9c36-c9b8b440952e.png)

**Comment by argyleink** [comment]
feature request: 
- high precision timing
- if reduced motion no millisecond updates
- css tip: use tabular nums
- when less than 24 hours (tbd) switch to hyper precision
