### ISSUE TITLE
Attendance module design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#223]
should:
- articulate how to attend (tickets, registration form, etc)
- articulate the process at a macro view
- marketing copy to help sell it
- reference to the code of conduct
- cta to get updates
- cta to stream

**Comment by argyleink** [comment]
consider making this a content block / module instead of a page, then:
could go on the homepage
could go on the venue page
could go in the FAQ page

**Comment by jakearchibald** [comment]
Agree with the module approach. It could also go on sessions pages before the event. "You wanna see this? Well here's how…".

In terms of the "question" label, what's the question?

**Comment by argyleink** [comment]
dunno why i put the question label, removing it!
