### ISSUE TITLE
User settings page design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#224]
should feature:
- logout
- delete history
- streaming/attending control
- clear favorited sessions (need this or is it duplicative to "delete history")
- push notification permission control

see also #212 

this page can be accessed by tapping your user profile avatar or the default user profile avatar in the top right of the nav

**Comment by jakearchibald** [comment]
I'd always imagined this as a kinda overlay when you tapped on the avatar, but I like this page idea much better. This would give us more room to explain what the streaming/attending control does too.

**Comment by argyleink** [comment]
#### updated switch ideas
![stream vs attend](https://user-images.githubusercontent.com/1134620/62734869-d7729600-b9de-11e9-8508-394a86880021.png)

**Comment by jakearchibald** [comment]
I'm still a little worried that it looks like the user is un-attending, as in they lose their ticket. Maybe we only have this switch during the event? I dunno, sorry, I don't have a good answer here.

**Comment by argyleink** [comment]
cool, i'm down with that comment. let's do this, i'll hold off on any more switch work, it's "nice to have" imo, since it could easily be a checkbox or radio group and be less debt. i'll focus on other aspects of the settings page and we can revisit this toggle (if needed).
