### ISSUE TITLE
Speakers collection page design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#226]
should:
- have emcee's up top
- be alphabetical (by last name)?
- have a link to schedule
- consider minimalist layout with hover interactions (mobile can visit user detail to get the links)

questions:
- should speakers who are speaking together be grouped together?

**Comment by jakearchibald** [comment]
The schedule/session index will contain speaker details. The speakers homepage module 'advertises' the speakers. What's the purpose of this page?
