### ISSUE TITLE
Guidelines page design

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#227]
- accessibility
- inclusion
- code of conduct
- link to terms & conditions
- link to privacy policy
- link to contact via email

**Comment by argyleink** [comment]
nothing surprising in this design, follows the patterns found on other content heavy pages

**note:**
- prototypes have been updated so this new page is accessible
- assumes data is a grouped list
- content was taken from the current [deployed guidelines page](https://developer.chrome.com/devsummit/community-guidelines/)

<br>

<details>
  <summary>Desktop v0.0.1</summary>

  ![Desktop - Guidelines](https://user-images.githubusercontent.com/1134620/63959819-eda1ce00-ca41-11e9-9836-20ebe7bddd0d.png)

</details>

<details>
  <summary>Mobile v0.0.1</summary>

  ![Go Phone – Guidelines](https://user-images.githubusercontent.com/1134620/63959820-eda1ce00-ca41-11e9-8d5a-adac8173756f.png)

</details>

**Comment by jakearchibald** [comment]
@carolrivero @vschupmann are you happy for the content to be in this form?

**Comment by vschupmann** [comment]
I actually like it a lot. 

Q: In the General section, at the end of the 2nd paragraph, there's linked text "Please see here" that I'm assuming goes to the original Community Guidelines doc. Is that right? If yes, please keep it.
