### ISSUE TITLE
Update footer links (desktop & mobile)

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#228]
They're dated and need rethought post nav update / IA updates. note: this is not for the links at the very very bottom, but the links above those. 

candidates:
- schedule
- sessions? (would make for a good footer link)
- speakers
- venue
- guidelines
- FAQs
- attendance (scrolls down to module in venue page)
- settings
- contact

**Comment by jakearchibald** [comment]
We shouldn't need comps for these unless you're changing the layout.

**Comment by argyleink** [comment]
thoughts? i did change the layout a little bit, mostly shook things out and aligned things to the grid

##### Footer :: Desktop
![footer-desktop](https://user-images.githubusercontent.com/1134620/62968255-83d9c100-bdbf-11e9-829e-463ee6b231c4.png)

##### Footer :: Mobile
![footer-mobile](https://user-images.githubusercontent.com/1134620/62968256-83d9c100-bdbf-11e9-937c-a90c3399e09d.png)

**Comment by jakearchibald** [comment]
PR #232

**Comment by surma** [comment]
This landed
