### ISSUE TITLE
A2HS

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#230]
Curious how much investment we want to put into add to homescreen? i feel like there are assignments from branding to engineering, support questions from ios to windows, etc.. i feel like there's lots of work sitting in this topic.

here's an initial draft of the work i'm imagining we could do for nice a2hs ux:
- [ ] **icons**: run a custom build script against a few (ios, android) high res sources? i can produce this, but would like to lean on what the branding team comes up with. 
- [ ] **splash screens**: kinda similar story as icons
- [ ] **theme colors**: meta, status bar type, manifest.json
- [ ] **cache**: precache, settings ui, etc
- [ ] **standalone**: disable ptr, show back btn, etc
- [ ] **offline ui**: `const { isOnline } = navigator`, `window.addEventListener('online', e =>`, etc that we can use to give our app that offline polish. like, maybe we show how to handle lie-fi gracefully, which includes some nice ux to tell the user how the app is responding to the unreliability 🤷‍♂ 

scope creep central, and can already hear jake healthily suggesting to not shove tech into the story for no reason 😄 i think we could make this conf site install faster and feel as fast or faster than a native app. 

stretch goal maybe? 
curious where y'all're at here? 
what did i miss?

**Comment by surma** [comment]
> Icons
> Splashscreens

We got away in PROXX with just one 1024x1024 icon and a favicon. Not sure we need more than that.

> Theme Color

I think it's part of a good design.

> Cache

We 100% want offline support. It's a requirement.

> Standalone

Not sure. I think part of the story is that this is just a website, not necessarily an "app". So I think we could go with `"display": "browser"`

> Offline UI

We could do things like fade-out links that are unavailable. But we shouldn't tie functionality to this state.

**Comment by argyleink** [comment]
jake and i decided we dont need this, it's not adding to the experience in this case. a website is great.
