### ISSUE TITLE
Venue/location page

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#236]
Question from @vschupmann: Should https://developer.chrome.com/devsummit/location existi on the new site?

We don't have time to add a new page for the 20th, but it's something we should think about for the days leading up to the event.

@vschupmann if there's any info on this page you think we need for the 20th, can you add it to the FAQ? If we're including transport info, are we sure it's up to date?

**Comment by jakearchibald** [comment]
cc @harleenkbatra08

**Comment by vschupmann** [comment]
I agree it is too late to add this in time for this launch. Let's back burner it until next time. It is a nice to have, but it isn't crucial to registration.

**Comment by vschupmann** [comment]
Now that registration has begun, we're getting questions about transportation, hotels, and the like. Is there a page design for [this](https://docs.google.com/document/d/1VgzTEYm1IQ9dwbH2pGQd2jO8-I_wPL2nB9Qf_Hs3LFY/edit#heading=h.5h3v8npab2s8
) that I can start to fill in?

**Comment by surma** [comment]
Cc @argyleink

**Comment by argyleink** [comment]
i was going to call this "venue," but does "location" have precedence? 

see #219 for details around the venue page design so far (hint: it's not much yet)

**Comment by jakearchibald** [comment]
Closing in favour of https://github.com/GoogleChrome/devsummit/issues/256
