### ISSUE TITLE
Schedule page design v2

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#243]
- [x] current session
- [x] current time
- [x] past session
- [x] past time
- [x] past day
- [x] sessions with video links

any other interesting states or functionality we want to strive for?

**Comment by argyleink** [comment]
![Desktop - Schedule – States](https://user-images.githubusercontent.com/1134620/67132491-df5c6c80-f1bd-11e9-85a4-27d5b7a3df2b.png)

**Comment by argyleink** [comment]
decision: current talk is enough

**Comment by argyleink** [comment]
![Desktop - Schedule – 2](https://user-images.githubusercontent.com/1134620/67977483-6c97bc00-fbd5-11e9-9e51-a73783d1ace4.png)

- [ ] nice to have "jump to" links for schedule visitors during the conf
- [ ] nice to have relevant copy cc @vschupmann

**Comment by vschupmann** [comment]
The current copy is"

> Every session is available through Livestream during the event, and available after the event on the Chrome Developers YouTube channel.

Proposed new copy is under review our team's "Content Plan" Google doc.

**Comment by argyleink** [comment]
current copy is still good for "during" state 👍
