### ISSUE TITLE
Implement venue page

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#256]
Design: https://github.com/GoogleChrome/devsummit/issues/219

This includes the lifestream promo (https://github.com/GoogleChrome/devsummit/issues/256) which appears on other pages.

**Comment by vschupmann** [comment]
@argyleink 

Here are some short defs for the Sandbox area, as promised!

Sessions
Sessions are a chance to learn about Chrome's newest technologies directly from Chrome engineers and leadership. Here you’ll see presentations and demos on our latest features and updates from the staff who helped build them.

Lightning Talks
A lightning talk is very short and focused presentation that lasts only a few minutes, using a format that introduces urgency. This style of micro presentation allows many speakers to present in a single session at a forum, thereby quickly transferring information and avoiding “death by powerpoint” at conferences

Codelabs
Google Developers Codelabs provide a guided, tutorial, hands-on coding experience by stepping you through the process of building a small application, or adding a new feature to an existing application.

Office Hours

Office Hours are your chance to meet one-on-one with Chrome experts to ask all your technical questions! Here, you’ll have an opportunity to receive advice and tips on your specific app-related projects.

Sandbox
A sandbox is a dedicated space to explore, learn, and play with our latest products and platforms via interactive demos, physical installations, and more.

**Comment by vschupmann** [comment]
What is a review clinic? Can someone give a short description and then I can create a definition that is in line with the others?
