### ISSUE TITLE
Session URL design

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#260]
Options:

1. `/sessions/making-websites-faster/`
1. `/sessions/2019-09-06/making-websites-faster/`(where 2019-09-06 is the session day)
1. `/sessions/2019-09-06/1100-making-websites-faster/` (where 1100 is the time)

I'm leaning towards 1, because:

* URL still works if session time changes.
* Session time is mostly irrelevant after the conference.

**Comment by surma** [comment]
Agreed. +1 to #1

**Comment by jakearchibald** [comment]
Let's call it decided then.
