### ISSUE TITLE
Indoor map

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#262]
Can't find one yet (so may need to generate it 👎 ) but would be nice to have an indoor map for when you're there in person and wondering where everything is.

**Comment by vschupmann** [comment]
I'm checking around for a floor plan too.  Seems like we should have one on the events team.

**Comment by argyleink** [comment]
![image](https://user-images.githubusercontent.com/1134620/64718709-9d802e00-d47b-11e9-9a05-3995940be132.png)

![image](https://user-images.githubusercontent.com/1134620/64718717-a1ac4b80-d47b-11e9-8cb6-9fc6bcb4fa74.png)

**Comment by vschupmann** [comment]
Those are perfect.

**Comment by argyleink** [comment]
latest

![Indoor Map v0 0 2](https://user-images.githubusercontent.com/1134620/65286858-e8421b80-daf5-11e9-8be1-d739bc617827.png)
