### ISSUE TITLE
Odd scripts in content layout

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#264]
https://github.com/GoogleChrome/devsummit/blob/master/src/_includes/layouts/content/index.njk

There's some weird `<script type="a">` stuff here which I assume was left over from debugging?

**Comment by surma** [comment]
Aw shit. Yeah, that’s debugging left-overs. I’ll fix this after we’ve landed our PRs.

**Comment by jakearchibald** [comment]
Fiiixed
