### ISSUE TITLE
web.dev promo

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#271]
there room somewhere for a web.dev promo to feel natural?

**Comment by argyleink** [comment]
Amongst all the types I made, turned out subtle just never fit, rather having a web.dev module that matches the rest of the CTA style or user education modules worked best. On brand with CDS, on brand with web.dev. Felt appropriate, unsurprising, and non-disruptive. Also, as a module, it can move around

![Screen Shot 2019-09-26 at 11 44 08 AM](https://user-images.githubusercontent.com/1134620/65715940-fa224200-e052-11e9-831f-0bcd378d680f.png)

Messaging is from the web.dev homepage, felt it was great. 

Thoughts? Requests?

**Comment by robdodson** [comment]
LGTM :)

**Comment by vschupmann** [comment]
+1 LGTM

**Comment by harleenkbatra** [comment]
I like it, as long as others on the team are happy. I was going for something a lot more subtle and Jake wasn't fully convinced, so would be good to get his thoughts on this one :)
