### ISSUE TITLE
Schedule is showing only location adjusted times

### ISSUE THREAD

**Issue by jakubkoziol** [GoogleChrome/devsummit#29]
All times in the schedule are adjusted based on your current location without an easy way of changing it back to the original time zone. It makes planning for the actual event very inconvenient if you live anywhere outside of the PST.

**Comment by paullewis** [comment]
I can look at adding a switch. Why is it inconvenient, just out of interest?

**Comment by jakubkoziol** [comment]
Having to schedule something else during the day or planning on the travel are two big things that come to mind. If you're going to attend an event the information is only relevant to you in the time zone the event is being held.

It's a great feature for streamed stuff but even then it's good to have a local time reference.

Which also made me realize that specific session pages don't have the time listed at all. Feels like a convenient bit of information on the page that you can send to someone directly.

Other than that the UX seems to be pretty good!

**Comment by paullewis** [comment]
I have fixed this. It's now totally optional :)
