### ISSUE TITLE
page load jank/shift from fluid image sizes

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#295]
we should do a pass where we set some sizes on images so that they dont need to load to get a size. i can see icons and images loading async and causing layout jumps when they complete. noticed it in our global nav first, then in subsequent modules. 

resolution is straight forward, but tedious

ping me if you want a repro example or this ticket doesnt make sense

**Comment by jakearchibald** [comment]
Huh, I thought I'd dealt with this. Specific examples are welcome.

**Comment by argyleink** [comment]
![load-jank](https://user-images.githubusercontent.com/1134620/66227139-69221b00-e691-11e9-92b5-77a6f09cce9e.gif)

from my limited testing, it looks more specifically like:
- font loading relayout
- image width needing specified to?

**Comment by jakearchibald** [comment]
I think it's fonts rather than images. I'm not even sure we can do anything about it. Webfonts suck.

https://github.com/w3c/csswg-drafts/pull/4370
https://bugs.chromium.org/p/chromium/issues/detail?id=898083

**Comment by jakearchibald** [comment]
Hey @tabatkins! I'm back with my favourite web font bugbear 😄.

Even without `font-display: optional`, do you think we should avoid a layout shift for cached web fonts?

**Comment by tabatkins** [comment]
That feels like quality-of-implementation, no? Feel free to file a Chrome bug on it, yeah.
