### ISSUE TITLE
Timezone-adjusted schedule shows wrong times

### ISSUE THREAD

**Issue by oslego** [GoogleChrome/devsummit#296]
![cds-schedule-timezone](https://user-images.githubusercontent.com/63899/65589944-350c7300-df8a-11e9-8fd0-71e9e679dcd6.jpg)

The times for the schedule on the second day are adjusted incorrectly. 

Steps to reproduce:
- Travel to Central Europe
- Open https://developer.chrome.com/devsummit/schedule/
- Use the "schedule timezone" toggle

Expected result:
- Both event days show correctly adjusted times (+9 hours)

**Comment by surma** [comment]
What about the schedule is incorrect? Each talk has been moved by +9 hours as far as I can tell form your screenshot.

**Comment by oslego** [comment]
Oh rats! You're right, indeed. This is the side-effect of #296 with sessions spanning into the next day.

This is really confusing. I was expecting to see the 2-day schedule *grouped by event day* and offset by timezone, instead of *grouped by calendar day* and strictly ordered by time.

I wanted to plan ahead whether I should plan to watch the live stream the morning of the second day.

**Comment by surma** [comment]
Let's continue the discussion in the other issue.

For now, this is WAI :D
