### ISSUE TITLE
Implement promo module

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#301]
I'm feeling like these little promo comps are establishing a module pattern. There's a formula to follow, with a couple of options, and then we can kinda let marketing go nuts? promote what they wanna?

@jakearchibald thoughts?

<br>

<details>

<summary>promo modules comp</summary>

![Screen Shot 2019-09-27 at 10 03 13 AM](https://user-images.githubusercontent.com/1134620/65787611-3c5c8980-e10e-11e9-9563-a32eda353eb1.png)

</details>

**Comment by jakearchibald** [comment]
lgtm. I'll add it to my list.

**Comment by jakearchibald** [comment]
This is done in https://github.com/GoogleChrome/devsummit/pull/324
