### ISSUE TITLE
UX during conference

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#307]
@argyleink all of this is open to interpretation/discussion. Let me know what you think:

Before conference:

* Reduce size of header on mobile (so some subsequent content is above the fold)
* A countdown?

During conference:

* YouTube iframe for livestream.
* Info about session on now. Session title, abstract, time started, time ends. Since we've got times here we should have the timezone switcher.
* Info about session on next.
* Should we show the schedule for the rest of the day too?

**Comment by surma** [comment]
> YouTube iframe for livestream.

I'd like to PE with @beaufortfrancois’s PiP. That way people should we able to navigate to the schedule or other things while watching the live stream, no?

> Info about session on now. Session title, abstract, time started, time ends. Since we've got times here we should have the timezone switcher.

Should we a “Go to Now” button on the schedule that just does `scrollIntoView()`?

**Comment by beaufortfrancois** [comment]
Hey @surma, let me know how I can help.

**Comment by jakearchibald** [comment]
PiP doesn't allow for navigation as far as I know, so a pop-out might be better. Although, YouTube's UI already allows for that.

> Should we add a “Go to Now” button on the schedule that just does `scrollIntoView()`?

Is that better than just listing the remainder of the day's schedule on the homepage?

During JSConf BP I went to the site a lot just to find out what was on now & following. We we should make that as easy as possible.

**Comment by surma** [comment]
> PiP doesn't allow for navigation as far as I know,

@beaufortfrancois Is that true? :(

> Is that better than just listing the remainder of the day's schedule on the homepage?

Where do I find the previous schedule? Like, what if I forgot the name of the speaker of the talk I just saw or something.

**Comment by jakearchibald** [comment]
I was thinking we leave the schedule page as-is (although maybe include the livestream at the top, along with now & next)

**Comment by surma** [comment]
OOH, I didn't parse the “remainder of the day's schedule **on the homepage**” correctly.

Yeah, that works. We should probably fade out past sessions or something (and I still think a “scroll to now” would be nice, but defo optional). Okay, just violent agreement then.

**Comment by jakearchibald** [comment]
Yeah, a way to signal 'now' on the schedule would also be nice.

**Comment by argyleink** [comment]
lovely ideas i'll add to my design task list 👍

**Comment by argyleink** [comment]
lemme know if i'm recapping this well:

**homepage requests:**
- before conf
  - reduce header to try and bring something above the fold
  - countdown 
- during conf
  - ensure livestream is easy to find (likely have it in multiple places)
  - current session
  - next session
  - ...rest of the schedule

**global requests/implications**
- countdown is comin, we could put that wherever we like. i like the concept of putting it anywhere the user is thinking about time: home, schedule, livestream pages
- current/next session indicated on schedule page
- past sessions marked on schedule page

> During JSConf BP I went to the site a lot just to find out what was on now & following. We we should make that as easy as possible.

^ fully agree

i'm curious about notifications? are those going to make it? will be have 1 global notification request for all of CDS, or can I subscribe to certain sessions and get a push when theyre about to start?

**Comment by jakearchibald** [comment]
Looks good to me. Couple of notes:

> ensure livestream is easy to find

I think we should put the livestream at the top of the home page, perhaps the schedule page too.

> i'm curious about notifications? are those going to make it?

Nah 😢, login isn't going to make it.

**Comment by jakearchibald** [comment]
@argyleink how's it going with this? Looking to plan my dev time

**Comment by argyleink** [comment]
schedule designs for "during conf" work can be found here #243
countdown comps can be found here #220

<details>
<summary>Nav Desktop :: During & After</summary>

![Desktop  Nav  during and after](https://user-images.githubusercontent.com/1134620/67792990-5522cc80-fa37-11e9-9586-dfa21d0f6709.png)

</details>

<details>
<summary>Nav Mobile :: During & After</summary>

![Mobile  Nav  during and after](https://user-images.githubusercontent.com/1134620/67792991-5522cc80-fa37-11e9-84f4-4533dc2abd93.png)

</details>

<details>
<summary>Header Desktop :: During</summary>

![Home - Desktop – During Event](https://user-images.githubusercontent.com/1134620/67794070-476e4680-fa39-11e9-99ec-97c2ed88fec6.png)

</details>

That unblocks you for a bit yeah? Let me know what I missed as you dig in 👍

**Comment by jakearchibald** [comment]
I was more thinking of what we discussed in https://github.com/GoogleChrome/devsummit/issues/307#issuecomment-538578615.

During the conference, when the user goes to the homepage, they see a YouTube embed, along with something that tells them about the session they're watching (title, abstract, speakers), and then the remaining schedule of the day.

If I'm at a conference, I tend to go to the site to find out something about the current session (eg, I want to follow the speakers on twitter), and I want to know what's happening next. Is it a break, is it another session?

If I'm navigating to a conference that's happening remotely *right now*, the live stream should be front-and-centre.

**Comment by argyleink** [comment]
i guess the word livestream is hard to pin down:
- livestream primary global cta
- livestream module
- livestream actual experience (this is the demo we got from sam??) or something more minimal for the homepage? or do we just punt to youtube for a full streaming experience? (will there be chat?)

help me understand exactly what you need and i'll make it. your comment helps me shape it a bit, but can you break down the tech you intend to use for it? maybe we have a short meeting about it for quick alignment?

**Comment by vschupmann** [comment]
Related to this, I'll try to pin down the YT livestream URL and any other links you might need. I'll add them to our Content Plan.

**Comment by jakearchibald** [comment]
@argyleink let me know if this helps:

From the top, the home page will contain, in this order:

1. The header. Similar to how it is already on desktop. Much smaller on mobile, so the next content is easier to see.
1. Before the event: Countdown, or some other placeholder. During the event: YouTube livestream embed.
1. During the event: Info on the session happening now. Title, abstract, speakers, time started.
1. During the event: Info on the session happening next.
1. During the event: The remaining schedule of the day.
1. Before the event: The rest of the stuff we currently have on the homepage.

**Comment by argyleink** [comment]
that ux flow makes sense (pretty much 1:1 your initial comment on this ticket), but i'd love to chat tech details and a few other things. most the requests you have here are homepage related, the rest of the stateful work delivered is good though?

**Comment by jakearchibald** [comment]
@argyleink yeah, it's just the homepage. Rest looks great.

Oh, we should also be ready to put a youtube embed on session pages, when the video of the talk is out. This should replace the box that says the date & time, since that info is now redundant.

I'll set up something for the calendar.

**Comment by argyleink** [comment]
![Home - Desktop – During Event - v1](https://user-images.githubusercontent.com/1134620/67978497-77535080-fbd7-11e9-80e9-c600b4aa427c.png)

v1 ready for review, thoughts?

**Comment by jakearchibald** [comment]
Yeah, I like this! I think I'd go for "Started 10 minutes ago" rather than "minutes left".

Eg: "Started 2 minutes ago" - oh ok, I haven't missed much, I'll start watching now.
"Started 20 minutes ago" - meh I'll pick up the next session.
"20 minutes left" - 🤷‍♂️

Also, I think the "next" bit should have "In 20 minutes" or whatever.

**Comment by argyleink** [comment]
![Home - Desktop – During Event - v2](https://user-images.githubusercontent.com/1134620/68038892-2ea7a000-fc88-11e9-9a1a-c251b7654c15.png)

nice feedback, I like it 👍

**Comment by argyleink** [comment]
![feature-phone-homepage-during](https://user-images.githubusercontent.com/1134620/68040484-a6c39500-fc8b-11e9-8514-5231f5389d27.gif)


<details>

<summary>Mobile Comp - v1</summary>

![Home - Feature Phone – During Event - v1](https://user-images.githubusercontent.com/1134620/68040326-5ba98200-fc8b-11e9-83fd-a1fc3bc33d15.png)

</details>

**Comment by jakearchibald** [comment]
Could you add these to the XD?
