### ISSUE TITLE
Remove dead car park link

### ISSUE THREAD

**Issue by coliff** [GoogleChrome/devsummit#312]
the link: http://parking.hearstbuildingsf.com/ is dead

**Comment by surma** [comment]
cc @vschupmann

**Comment by vschupmann** [comment]
Looking into it now.

**Comment by vschupmann** [comment]
I've tried calling the parking garage and GPJ (our agency that supplies this information) and could not get any help with this. We have three other parking garages listed so I'm thinking we should remove the hearts parking center from our website. WDYT?

**Comment by surma** [comment]
sgtm!
