### ISSUE TITLE
hero brand image background shape color should be shared with brand divider bg

### ISSUE THREAD

**Issue by argyleink** [GoogleChrome/devsummit#316]
it'd be nice if each page had a brand secondary color (which it does now) but that was shared with any dividers on that page. right now they mismatch and there's not really any rhyme or reason, so i'd like to define that pattern!

pattern:
for each page assign a secondary brand color (or let someone pass it via data so it can be manually customized)
each hero header for the page uses that color for the bg color of it's brand shape
each divider uses that color as the background tint

can make a comp if this is confusing. lemme know

**Comment by vschupmann** [comment]
I'm one of those visual people - would like to see more color on the pages. It would also give us more of a bespoke look and feel. Set up apart from the other websites. 

Do you have a color palette from the design team? Sometimes they come with the branding asset stuff.
