### ISSUE TITLE
[Suggestion] Add dates 📅 and times 🕰 to each session page. 

### ISSUE THREAD

**Issue by juniperbelmont** [GoogleChrome/devsummit#32]
Similar to #31 , it would be -really- helpful to have the date and time information on each of the session pages. I can set notifications, but the page itself doesn't tell me what time the notification will go off.

<img width="600" alt="screen shot 2016-10-28 at 11 54 13" src="https://cloud.githubusercontent.com/assets/4591840/19818614/6189c1f0-9d05-11e6-8270-9200158afc80.png">

**Comment by paullewis** [comment]
Yep, added them 👍 Thanks for the suggestion!

**Comment by juniperbelmont** [comment]
Maybe next time I'll get up off my butt and send in a PR. 🙄
