### ISSUE TITLE
is-pwa check.

### ISSUE THREAD

**Issue by hemanth** [GoogleChrome/devsummit#33]
Do you like a PR changing [this](https://github.com/GoogleChrome/devsummit/blob/master/.travis.yml#L22) to use [this](https://npm.im/is-pwa)? 🤔

//cc @paullewis

**Comment by surma** [comment]
Your first link doesn’t go anywhere in particular. Not sure what you want to replace here

**Comment by hemanth** [comment]
Fixed [it](https://github.com/GoogleChrome/devsummit/blob/master/.travis.yml#L22).

**Comment by jakearchibald** [comment]
We're restarting the project, so I'm closing this

**Comment by hemanth** [comment]
👍
