### ISSUE TITLE
FAQ page -- Add a list of the questions at the top (or side)

### ISSUE THREAD

**Issue by vschupmann** [GoogleChrome/devsummit#337]
Would it be possible to add a summary/list at the top of the page (or side of the page) so you can quickly scan the FAQ questions? Even better if there could be a link to each question. It’s a very long FAQ --- and even though I know what is in there I still have trouble finding things sometimes.

**Comment by jakearchibald** [comment]
@argyleink what do you think? If it's a big effort I don't want to delay getting the "during conference" site ready.

**Comment by vschupmann** [comment]
That's would be a good solution at this point given we have only 2 weeks before the summit. If we had more time and resources, it would be optimal to have a list of the questions for scanning purposes.

**Comment by jakearchibald** [comment]
PR https://github.com/GoogleChrome/devsummit/pull/344
