### ISSUE TITLE
Issue with templating engine on mailing system

### ISSUE THREAD

**Issue by fejes713** [GoogleChrome/devsummit#342]
## What
When receiving an email about updates on Chrome Dev Summit, the email footer is not populated with real data but instead shows syntax from templating engine.

## Screenshot
![image](https://user-images.githubusercontent.com/25749162/68150253-a0f5da00-ff3f-11e9-97b2-5a33eafd5646.png)
 

_I have no idea where to put this but it's a small, easy fix - hopefully it's okay to leave it here_

The website looks amazing though, I really like it :octocat: See you in a few days 🎉

**Comment by surma** [comment]
Thanks for letting us know.

We have nothing to do with the emails being sent out, so I'll just ping this to @vschupmann.

**Comment by vschupmann** [comment]
Thank you for flagging this! Luckily this is a very simple fix we can take
care of so the problem doesn't happen in future communications.

--Viv

**Comment by fejes713** [comment]
@surma I thought so but I had no idea where to put it. 

I am closing this since @vschupmann will solve it and it has nothing to do with the website.
