### ISSUE TITLE
[Suggestion] Add "Back to top" button in the schedule view.

### ISSUE THREAD

**Issue by kevin2r** [GoogleChrome/devsummit#36]
When I browse the talks for day 1, at the end I have to scroll the entire page to the top to see the schedule for day 2. With a "back to top button" should be easier to do. Another solution is to add a button to switch directly to day 2.

**Comment by paullewis** [comment]
True! I shall add one.

**Comment by jakearchibald** [comment]
Closing, as we're restarting the project
