### ISSUE TITLE
Lack of info about keynote, eg day/time

### ISSUE THREAD

**Issue by jakearchibald** [GoogleChrome/devsummit#394]
https://deploy-preview-388--cds2019.netlify.app/devsummit/schedule/keynote/

I guess you're waiting on us for content?

**Comment by jakearchibald** [comment]
@johnrich85

**Comment by johnrich85** [comment]
hmm, we already have date/time I believe but it wasn't included on the designs. We don't have any other content though AFAIK. Can pop those on, if anything else needs adding though let me/Niamh know

**Comment by jakearchibald** [comment]
Looks fixed!
