### ISSUE TITLE
Discussing lighthouse issues

### ISSUE THREAD

**Issue by ramlmn** [GoogleChrome/devsummit#47]
Issues:
* **Not enough contrast ratio on some elements:**

  *Problem:* The problem is text elements are placed on top of SVG's. Lighthouse assumes that these elements have a background color of nearest parent element(`body` in most cases, which has a background of `#fafafa`), even when these elements visually have background that of SVG's.

  *Dirty fix:* Apply colors of SVG to any of the parent elements.

  For example:
  ``` html
  <footer class="footer">
    <div class="footer__content" role="presentation">
      <p>&copy; Google 2016</p>
      <p>
        <a target="_blank" rel="noopener" href="http://www.google.com/intl/en/policies/privacy/">Privacy</a> &amp;
        <a target="_blank" rel="noopener" href="http://www.google.com/intl/en/policies/terms/">Terms</a>
      </p>
      <p>
        <a href="/devsummit/code-of-conduct">Code of Conduct</a>
      </p>
    </div>
    <svg width="100%" height="100%" preserveAspectRatio="none" viewBox="0 0 1224 302">
      <polygon x="0" y="0" fill="#F0F0F0" points="0 20 1224 0 1224 302 0 302"></polygon>
      <polygon x="0" y="0" fill="#4D6BC3" points="0 226 1224 194 1224 302 0 302"></polygon>
    </svg>
  </footer>
  ```
  The color of svg(`#4D6BC3`) can be applied to `.footer__content > p` as `background-color`(and some other tweaks) so that lighthouse knows that.

  This is a dirty hack, you may or may not like it, if you want Lighthouse score.

* **No:** `<meta name="theme-color">`

**Comment by paullewis** [comment]
Yeah I'm summarily ignoring the background color issue to be honest. Lighthouse defers to axe for its a11y checks, and I wonder if there's a way to help it to understand that it's not white on transparent.

The theme color... I thought I had that. Fixed it in 1d8de2e.
