### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by nagygergo** [GoogleChrome/devsummit#56]
Browsing trough the [pwa.rocks](https://github.com/pwarocks/pwa.rocks) repository I found out that the devsummit site throws internal server error with stack trace :frowning: for the following links:  
https://developer.chrome.com/devsummit/sessions/
https://developer.chrome.com/devsummit/sessions/progressiveapps

You might want to take a look at it. :sweat_smile:

**Comment by paullewis** [comment]
Thanks :)
