### ISSUE TITLE
Some instances of .bind(this) instead of arrow function?

### ISSUE THREAD

**Issue by domfarolino** [GoogleChrome/devsummit#57]
This isn't an issue per se; I'm just curious as to whether or not there is a rationale behind using `.bind(this)` in some anon callbacks (I see this mainly in [scripts/cds.js](https://github.com/GoogleChrome/devsummit/blob/master/scripts/cds.js)) when an arrow function could have been used to preserve the lexical `this`. In some cases it is unavoidable, like when passing a class function as a callback like [here](https://github.com/GoogleChrome/devsummit/blob/master/scripts/cds.js#L47), but the ones I'm referring to seemingly could utilize arrow functions in place of a call to `.bind(...)` and I was just wondering if there was a specific reason for choosing one over the other. Consistency?

Ex:

 - [Here](https://github.com/GoogleChrome/devsummit/blob/master/scripts/cds.js#L116)
 - [And here](https://github.com/GoogleChrome/devsummit/blob/master/scripts/cds.js#L132)

**Comment by surma** [comment]
@paullewis set out to write this project without Babel and Safari 8 doesn’t support fat-arrow functions. [We have added babel](https://github.com/GoogleChrome/devsummit/blob/a9d0d121a83630bb612bc5001d3beed50283d9be/package.json#L15) in the meantime, but just for minification, not for transpilation.
