### ISSUE TITLE
All navigations fail to load after one view fails to load

### ISSUE THREAD

**Issue by domfarolino** [GoogleChrome/devsummit#59]
Suppose a new user comes to the site. Initial site content loads, then the network goes out. While offline, the user tries to navigate from Schedule to either Location or Code of conduct. Since none of that page data is loaded in the SW cache yet (never been visited or prefetched it seems) we see the grey background and the spinner as expected:
<img width="867" alt="screen shot 2016-12-03 at 6 31 22 pm" src="https://cloud.githubusercontent.com/assets/9669289/20862917/eccf3018-b986-11e6-84a3-7fd3c664c04b.png">

If the user then goes online and tries to navigate from that failed page to any other page (previously visited & cached or not, doesn't matter) the document loads successfully over the internet however the view is never transitioned onto the screen.

I think the application should in a sense be able to "recover" from an outage like this and continue functioning once a successful connection is established again as long as the critical app logic is loaded.

Steps to reproduce:

 - Navigate to: https://developer.chrome.com/devsummit/
 - DevTools -> Application Tab -> "Clear all" (with all boxes checked)
 - Refresh the page
 - Network tab -> check "Offline" checkbox
 - Navigate to either "Location" or "Code of Conduct"
 - Network tab -> check "Offline" checkbox
 - Try to navigate back to either "Schedule" or "Code of Conduct"
 - No page should successfully load from this point on until a page refresh

I think I've tracked it down to the [`_hideAreas ()` function in `cds.js`](https://github.com/GoogleChrome/devsummit/blob/master/scripts/cds.js#L158). From what I can tell the Promise never gets fulfilled when the internet goes out since the `transitionend` event never gets fired on the masthead.

I threw in a small hack to get it to work locally after a few seconds by putting `setTimeout(resolve, 3000)` before we add the event listener. This basically says "Hey, if we haven't resolved in 3 seconds we need to fulfill this thing". So on a new navigation when internet is established again we wait three seconds and then the application works again. This is not a solution, just shows where the issue is. Ideally we'd `reject()` if we know for sure the event will never be fired. If @paullewis or @surma sees this as an issue too I wouldn't mind submitting a fix, but I'm a little stuck on how we could be sure this won't resolve. Thoughts?

**Comment by surma** [comment]
Hey @domfarolino,

Sorry for the long delay. Had stuff happening. I think you found the cause of this issue. So if you feel like submitting a patch, I’d be happy to review it :)
