### ISSUE TITLE
Help. How to fix?

### ISSUE THREAD

**Issue by DrAndromeda** [GoogleChrome/devsummit#61]
[MacBook-Pro-Kim:~/desktop/444/devsummit] Andromeda% sudo npm run build

> chrome-dev-summit-2016@9.0.2 build /Users/Andromeda/Desktop/444/devsummit
> npm run build-css && npm run build-js && npm run build-vr && npm run build-resource-list

> chrome-dev-summit-2016@9.0.2 build-css /Users/Andromeda/Desktop/444/devsummit
> npm run make-css-folder && node-sass sass/ -o static/styles && npm run clean-css

> chrome-dev-summit-2016@9.0.2 make-css-folder /Users/Andromeda/Desktop/444/devsummit
> mkdirp static/styles

Rendering Complete, saving .css file...
Wrote CSS to /Users/Andromeda/Desktop/444/devsummit/static/styles/cds.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/Andromeda/Desktop/444/devsummit/static/styles/code-of-conduct.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/Andromeda/Desktop/444/devsummit/static/styles/home.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/Andromeda/Desktop/444/devsummit/static/styles/inline.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/Andromeda/Desktop/444/devsummit/static/styles/live.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/Andromeda/Desktop/444/devsummit/static/styles/location.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/Andromeda/Desktop/444/devsummit/static/styles/schedule.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/Andromeda/Desktop/444/devsummit/static/styles/sessions.css
Wrote 8 CSS files to /Users/Andromeda/Desktop/444/devsummit/static/styles

> chrome-dev-summit-2016@9.0.2 clean-css /Users/Andromeda/Desktop/444/devsummit
> node ./build/clean-css.js

> chrome-dev-summit-2016@9.0.2 build-js /Users/Andromeda/Desktop/444/devsummit
> rollup -c && babel static/scripts/bootstrap.js --presets babel-preset-babili --out-file static/scripts/bootstrap.js

Error: Couldn't find preset "es2015" relative to directory "/Users/Andromeda/Desktop"
    at /Users/Andromeda/Desktop/444/devsummit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:299:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/Andromeda/Desktop/444/devsummit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:270:20)
    at OptionManager.mergePresets (/Users/Andromeda/Desktop/444/devsummit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:259:10)
    at OptionManager.mergeOptions (/Users/Andromeda/Desktop/444/devsummit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:14)
    at OptionManager.init (/Users/Andromeda/Desktop/444/devsummit/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:12)
    at File.initOptions (/Users/Andromeda/Desktop/444/devsummit/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/Andromeda/Desktop/444/devsummit/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/Andromeda/Desktop/444/devsummit/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/Andromeda/Desktop/444/devsummit/node_modules/babel-cli/lib/babel/util.js:50:22)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build-js"
npm ERR! node v6.8.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! chrome-dev-summit-2016@9.0.2 build-js: `rollup -c && babel static/scripts/bootstrap.js --presets babel-preset-babili --out-file static/scripts/bootstrap.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chrome-dev-summit-2016@9.0.2 build-js script 'rollup -c && babel static/scripts/bootstrap.js --presets babel-preset-babili --out-file static/scripts/bootstrap.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chrome-dev-summit-2016 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c && babel static/scripts/bootstrap.js --presets babel-preset-babili --out-file static/scripts/bootstrap.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chrome-dev-summit-2016
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chrome-dev-summit-2016
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Andromeda/Desktop/444/devsummit/npm-debug.log

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.8.1
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! chrome-dev-summit-2016@9.0.2 build: `npm run build-css && npm run build-js && npm run build-vr && npm run build-resource-list`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chrome-dev-summit-2016@9.0.2 build script 'npm run build-css && npm run build-js && npm run build-vr && npm run build-resource-list'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the chrome-dev-summit-2016 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-css && npm run build-js && npm run build-vr && npm run build-resource-list
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs chrome-dev-summit-2016
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls chrome-dev-summit-2016
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Andromeda/Desktop/444/devsummit/npm-debug.log
[MacBook-Pro-Kim:~/desktop/444/devsummit] Andromeda%

**Comment by eriktrom** [comment]
Try with npm3 `npm i -g npm@3.10.9` - the `--scripts-prepend-node-path` breaking change explained [here](https://github.com/npm/npm/releases/tag/v4.0.0) is a likely culprit

I just tried w/ node 7.3.0, npm 4.0.5 and it does work, but i alias /usr/local/bin/node -> `~/.nvm/versions/node/v7.3.0/bin/node` when installing a new default version of node (bypassing the need for the new flag mentioned, which prepends the global node path to scripts run with `npm run x` IIRC)

hope things work out
