### ISSUE TITLE
Preserve old site

### ISSUE THREAD

**Issue by kosamari** [GoogleChrome/devsummit#64]
I find it useful when conference preserve sites from previous years. 
Seeing who was speaker, what was presented, what kind of activities happened. 
Perhaps we can have static archive on `https://developer.chrome.com/devsummit/2017/` or something??
cc @PaulKinlan

**Comment by kosamari** [comment]
- Things we may need to be careful is service workers. 
- I see 2017 & 2018 in branches. Is older years on other codebase or just in git history?
  - Especially, 2016 site was topic of @paullewis's dev diary video series. I thing its beneficial to keep it accessible somewhere on the web.

**Comment by samthor** [comment]
Do we need to preserve the old site, or just the old sessions/speakers? I am more a fan of having some pages containing 'old sessions' even in the new UI look and feel, since that might get maintained year over year.

**Comment by murielsilveira** [comment]
I really like @kosamari's points on preserving all sites from previous years.
It's a go-to for inspiration and information about that specific event.

**Comment by jakearchibald** [comment]
We'll include a review of previous sessions in the new site
